<!DOCTYPE html>

<html>

<head>

<meta charset="utf-8" />
<meta name="generator" content="pandoc" />
<meta http-equiv="X-UA-Compatible" content="IE=EDGE" />


<meta name="author" content="Kateřina Hudáčová, Benjamín Kunc" />


<title>Selected Topics of Psychometrics (NMST570)</title>

<script src="site_libs/header-attrs-2.11/header-attrs.js"></script>
<script src="site_libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="site_libs/bootstrap-3.3.5/css/bootstrap.min.css" rel="stylesheet" />
<script src="site_libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<style>h1 {font-size: 34px;}
       h1.title {font-size: 38px;}
       h2 {font-size: 30px;}
       h3 {font-size: 24px;}
       h4 {font-size: 18px;}
       h5 {font-size: 16px;}
       h6 {font-size: 12px;}
       code {color: inherit; background-color: rgba(0, 0, 0, 0.04);}
       pre:not([class]) { background-color: white }</style>
<script src="site_libs/navigation-1.1/tabsets.js"></script>
<link href="site_libs/highlightjs-9.12.0/default.css" rel="stylesheet" />
<script src="site_libs/highlightjs-9.12.0/highlight.js"></script>

<style type="text/css">
  code{white-space: pre-wrap;}
  span.smallcaps{font-variant: small-caps;}
  span.underline{text-decoration: underline;}
  div.column{display: inline-block; vertical-align: top; width: 50%;}
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
  ul.task-list{list-style: none;}
    </style>

<style type="text/css">code{white-space: pre;}</style>
<script type="text/javascript">
if (window.hljs) {
  hljs.configure({languages: []});
  hljs.initHighlightingOnLoad();
  if (document.readyState && document.readyState === "complete") {
    window.setTimeout(function() { hljs.initHighlighting(); }, 0);
  }
}
</script>








<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
img {
  max-width:100%;
}
.tabbed-pane {
  padding-top: 12px;
}
.html-widget {
  margin-bottom: 20px;
}
button.code-folding-btn:focus {
  outline: none;
}
summary {
  display: list-item;
}
pre code {
  padding: 0;
}
</style>



<!-- tabsets -->

<style type="text/css">
.tabset-dropdown > .nav-tabs {
  display: inline-table;
  max-height: 500px;
  min-height: 44px;
  overflow-y: auto;
  border: 1px solid #ddd;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs > li.active:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li.active:before {
  content: "&#xe258;";
  border: none;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs > li.active {
  display: block;
}

.tabset-dropdown > .nav-tabs > li > a,
.tabset-dropdown > .nav-tabs > li > a:focus,
.tabset-dropdown > .nav-tabs > li > a:hover {
  border: none;
  display: inline-block;
  border-radius: 4px;
  background-color: transparent;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li {
  display: block;
  float: none;
}

.tabset-dropdown > .nav-tabs > li {
  display: none;
}
</style>

<!-- code folding -->




</head>

<body>


<div class="container-fluid main-container">




<div id="header">



<h1 class="title toc-ignore">Selected Topics of Psychometrics (NMST570)</h1>
<h3 class="subtitle">Homework Assignment 1: Introduction (due: Oct 18, 2021)</h3>
<h4 class="author">Kateřina Hudáčová, Benjamín Kunc</h4>

</div>


<p></br></p>
<div id="read-and-comment-on-the-first-chapter-on-httpsperusall.com.-2-pts" class="section level4">
<h4>1. Read and comment on the first chapter on <a href="https://perusall.com" class="uri">https://perusall.com</a>. [2 pts]</h4>
<p>Done.</p>
</div>
<div id="run-the-code-for-the-first-chapter-available-on-course-webpage-httpwww.cs.cas.czmartinkovanmst570.html." class="section level4">
<h4>2. Run the code for the first chapter, available on course webpage <a href="http://www.cs.cas.cz/martinkova/NMST570.html" class="uri">http://www.cs.cas.cz/martinkova/NMST570.html</a>.</h4>
<p>Done.</p>
</div>
<div id="complete-the-caplearnr-online-tutorials-for-introduction-and-measurement-data.-attach-certificates.-4-pts" class="section level4">
<h4>3. Complete the CAPlearnR online tutorials for Introduction and Measurement data. Attach certificates. [4 pts]</h4>
<blockquote>
<p>Note: If you meet any issues, contact the the TA or the instructor before 8 AM of the due date.</p>
</blockquote>
<p>Completed.</p>
</div>
<div id="project-preparation-explore-the-czech-matura-data-as-described-below.-you-can-work-with-1-2-teammates-on-this-task.-all-teammates-names-have-to-be-included-on-your-answer-sheet.-4-pts" class="section level4">
<h4>4. Project preparation: Explore the Czech matura data as described below. You can work with 1-2 teammates on this task. All teammates names have to be included on your answer sheet. [4 pts]</h4>
<div id="a.-the-czech-matura-sample-data-is-available-in-the-shinyitemanalysis-package-as-czmaturas.-the-czmaturas.csv-file-is-available-on-course-webpage.-explore-the-czmaturas-dataset-with-r-andor-shinyitemanalysis.-load-the-data-and-write-some-basic-description-of-the-data-below.-how-many-rows-and-columns-does-it-contain-what-do-they-represent" class="section level5">
<h5>4a. The Czech matura sample data is available in the <code>ShinyItemAnalysis</code> package as <code>CZmaturaS</code>. The <code>CZmaturaS.csv</code> file is available on course webpage. Explore the <code>CZmaturaS</code> dataset with R and/or ShinyItemAnalysis. Load the data and write some basic description of the data below. How many rows and columns does it contain, what do they represent?</h5>
<blockquote>
<p>HINT: Use the <code>library()</code> function to load the package, and the <code>help()</code> function (or <code>?</code>) to learn more about the dataset. Use functions <code>dim()</code>, <code>names()</code>, <code>head()</code>, <code>str()</code>, and/or <code>summary()</code> to explore the data. Check how variables <code>SchTypeGY</code> and <code>Total</code> were computed.</p>
</p>
</blockquote>
<pre class="r"><code>library(tidyverse)
library(ShinyItemAnalysis)
library(shiny)
library(utils)
library(ggplot2)
library(psych)</code></pre>
<pre class="r"><code>#Package documentation
?&quot;ShinyItemAnalysis-package&quot;</code></pre>
<pre class="r"><code>#Loading the CzmaturaS dataset
data(&quot;CZmaturaS&quot;)</code></pre>
<pre class="r"><code>dim(CZmaturaS)</code></pre>
<pre><code>## [1] 2000   73</code></pre>
<details>
<summary>
<p><code>names(CZmaturaS)</code></p>
</summary>
<pre><code>##  [1] &quot;SchType&quot;    &quot;FirstAtt&quot;   &quot;SchTypeGY&quot;  &quot;o1&quot;         &quot;o2&quot;         &quot;o3.1&quot;       &quot;o3.2&quot;       &quot;o4&quot;         &quot;o5&quot;         &quot;o6&quot;         &quot;o7&quot;         &quot;o8.1&quot;       &quot;o8.2&quot;       &quot;o8.3&quot;      
## [15] &quot;o9.1&quot;       &quot;o9.2&quot;       &quot;o10&quot;        &quot;o11&quot;        &quot;o12&quot;        &quot;o13&quot;        &quot;o14&quot;        &quot;o15&quot;        &quot;o16.1&quot;      &quot;o16.2&quot;      &quot;o16.3&quot;      &quot;o16.4&quot;      &quot;o17&quot;        &quot;o18&quot;       
## [29] &quot;o19&quot;        &quot;o20&quot;        &quot;o21&quot;        &quot;o22&quot;        &quot;o23&quot;        &quot;o24&quot;        &quot;o25.1&quot;      &quot;o25.2&quot;      &quot;o25.3&quot;      &quot;o25.4&quot;      &quot;o26.1&quot;      &quot;o26.2&quot;      &quot;b1&quot;         &quot;b2&quot;        
## [43] &quot;b3.1&quot;       &quot;b3.2&quot;       &quot;b4&quot;         &quot;b5&quot;         &quot;b6&quot;         &quot;b7&quot;         &quot;b8.1&quot;       &quot;b8.2&quot;       &quot;b8.3&quot;       &quot;b9.1&quot;       &quot;b9.2&quot;       &quot;b10&quot;        &quot;b11&quot;        &quot;b12&quot;       
## [57] &quot;b13&quot;        &quot;b14&quot;        &quot;b15&quot;        &quot;b16&quot;        &quot;b17&quot;        &quot;b18&quot;        &quot;b19&quot;        &quot;b20&quot;        &quot;b21&quot;        &quot;b22&quot;        &quot;b23&quot;        &quot;b24&quot;        &quot;b25&quot;        &quot;b26&quot;       
## [71] &quot;Total&quot;      &quot;IRTscore&quot;   &quot;IRTscoreSE&quot;</code></pre>
</details>
<details>
<summary>
<p><code>head(CZmaturaS)</code></p>
</summary>
<pre><code>##   SchType FirstAtt SchTypeGY o1 o2 o3.1 o3.2 o4 o5 o6 o7 o8.1 o8.2 o8.3 o9.1 o9.2 o10 o11 o12 o13 o14 o15 o16.1 o16.2 o16.3 o16.4 o17 o18 o19 o20 o21 o22 o23 o24 o25.1 o25.2 o25.3 o25.4 o26.1
## 1     GY4        1         1  1  1    0    0  2  0  1  2    1    1    1    1    1   1  NA   1   1   3   2     2     2     2     2   4   3   4   5   4   1   3   1     3     6     2     4     5
## 2     ST1        1         0  1  1    0    0  2  2  1  2    1    1    1    1    0   1   0   1   0   0   2     1     2     1     2   4   3   2   4   4   1   3   2     3     6     1     2     5
## 3     ST1        1         0  0  1   NA   NA  2  2  1  2   NA   NA   NA    1    1   1   1   0   0   3   2     1     1     1     1   1   3   4   1   5   2   5   3     3     6     1     5     5
## 4     ST1        0         0  1  1    0    0  0 NA  1 NA    1    1    0   NA   NA   1  NA   1   0  NA   0     2     2     2     2   4   2   3   1   4   1   5   3     3     6     1     2     5
## 5     UTE        1         0  1  0    1    0  2  2  1  2    1    1    0    1    1  NA   0   1   1   0   1     2     1     2     1   5   4   4   2   4   5   5   2     5     6     1     2     5
## 6     GY8        0         1  0  0   NA   NA  0 NA NA NA    0    0    0    1    1   1   0   0   1   0   0     1     1     1     1   4   3   4   5   4   1   4   3     3     6     1     2     5
##   o26.2 b1 b2 b3.1 b3.2 b4 b5 b6 b7 b8.1 b8.2 b8.3 b9.1 b9.2 b10 b11 b12 b13 b14 b15 b16 b17 b18 b19 b20 b21 b22 b23 b24 b25 b26 Total     IRTscore IRTscoreSE
## 1     4  1  1    0    0  2  0  1  2    1    1    1    1    1   1   0   1   1   3   2   0   2   0   2   0   2   2   0   0   2   1    31  0.342881201  0.2661316
## 2     3  1  1    0    0  2  2  1  2    1    1    1    1    0   1   0   1   0   0   2   0   2   0   0   0   2   2   0   0   4   3    30  0.295988773  0.2630337
## 3     3  0  1    0    0  2  2  1  2    0    0    0    1    1   1   1   0   0   3   2   2   0   0   2   2   0   0   2   2   3   3    33 -0.005917671  0.2468540
## 4     3  1  1    0    0  0  0  1  0    1    1    0    0    0   1   0   1   0   0   0   0   2   2   0   2   2   2   2   2   4   3    28 -0.145702261  0.2422359
## 5     2  1  0    1    0  2  2  1  2    1    1    0    1    1   0   0   1   1   0   1   0   0   0   2   0   2   0   2   0   3   1    26 -0.085769847  0.2439559
## 6     3  0  0    0    0  0  0  0  0    0    0    0    1    1   1   0   0   1   0   0   2   2   0   2   0   2   2   0   2   4   3    23 -0.735423400  0.2498404</code></pre>
</details>
<details>
<summary>
<p><code>str(CZmaturaS)</code></p>
</summary>
<pre><code>## &#39;data.frame&#39;:    2000 obs. of  73 variables:
##  $ SchType   : Factor w/ 16 levels &quot;GY4&quot;,&quot;GY6&quot;,&quot;GY8&quot;,..: 1 10 10 10 16 3 10 1 1 10 ...
##  $ FirstAtt  : num  1 1 1 0 1 0 0 1 1 0 ...
##  $ SchTypeGY : num  1 0 0 0 0 1 0 1 1 0 ...
##  $ o1        : num  1 1 0 1 1 0 0 1 0 0 ...
##  $ o2        : num  1 1 1 1 0 0 0 1 1 1 ...
##  $ o3.1      : num  0 0 NA 0 1 NA NA NA 0 1 ...
##  $ o3.2      : num  0 0 NA 0 0 NA NA NA 0 1 ...
##  $ o4        : num  2 2 2 0 2 0 2 2 2 2 ...
##  $ o5        : num  0 2 2 NA 2 NA 2 2 2 2 ...
##  $ o6        : num  1 1 1 1 1 NA 0 1 1 1 ...
##  $ o7        : num  2 2 2 NA 2 NA 2 2 2 2 ...
##  $ o8.1      : num  1 1 NA 1 1 0 1 1 0 1 ...
##  $ o8.2      : num  1 1 NA 1 1 0 1 1 0 1 ...
##  $ o8.3      : num  1 1 NA 0 0 0 1 1 0 1 ...
##  $ o9.1      : num  1 1 1 NA 1 1 0 1 1 1 ...
##  $ o9.2      : num  1 0 1 NA 1 1 0 1 1 0 ...
##  $ o10       : num  1 1 1 1 NA 1 0 1 0 0 ...
##  $ o11       : num  NA 0 1 NA 0 0 0 1 1 1 ...
##  $ o12       : num  1 1 0 1 1 0 0 1 0 1 ...
##  $ o13       : num  1 0 0 0 1 1 NA 0 0 0 ...
##  $ o14       : num  3 0 3 NA 0 0 NA 3 0 0 ...
##  $ o15       : num  2 2 2 0 1 0 0 2 1 0 ...
##  $ o16.1     : num  2 1 1 2 2 1 2 1 1 1 ...
##  $ o16.2     : num  2 2 1 2 1 1 1 1 1 1 ...
##  $ o16.3     : num  2 1 1 2 2 1 1 1 1 1 ...
##  $ o16.4     : num  2 2 1 2 1 1 2 1 1 1 ...
##  $ o17       : num  4 4 1 4 5 4 2 4 5 4 ...
##  $ o18       : num  3 3 3 2 4 3 3 2 3 2 ...
##  $ o19       : num  4 2 4 3 4 4 1 4 4 4 ...
##  $ o20       : num  5 4 1 1 2 5 2 1 2 1 ...
##  $ o21       : num  4 4 5 4 4 4 4 4 1 4 ...
##  $ o22       : num  1 1 2 1 5 1 3 1 2 1 ...
##  $ o23       : num  3 3 5 5 5 4 5 5 5 5 ...
##  $ o24       : num  1 2 3 3 2 3 2 2 5 2 ...
##  $ o25.1     : num  3 3 3 3 5 3 4 3 4 3 ...
##  $ o25.2     : num  6 6 6 6 6 6 2 6 5 6 ...
##  $ o25.3     : num  2 1 1 1 1 1 5 1 2 1 ...
##  $ o25.4     : num  4 2 5 2 2 2 1 2 6 2 ...
##  $ o26.1     : num  5 5 5 5 5 5 1 5 2 5 ...
##  $ o26.2     : num  4 3 3 3 2 3 3 3 4 3 ...
##  $ b1        : num  1 1 0 1 1 0 0 1 0 0 ...
##  $ b2        : num  1 1 1 1 0 0 0 1 1 1 ...
##  $ b3.1      : num  0 0 0 0 1 0 0 0 0 1 ...
##  $ b3.2      : num  0 0 0 0 0 0 0 0 0 1 ...
##  $ b4        : num  2 2 2 0 2 0 2 2 2 2 ...
##  $ b5        : num  0 2 2 0 2 0 2 2 2 2 ...
##  $ b6        : num  1 1 1 1 1 0 0 1 1 1 ...
##  $ b7        : num  2 2 2 0 2 0 2 2 2 2 ...
##  $ b8.1      : num  1 1 0 1 1 0 1 1 0 1 ...
##  $ b8.2      : num  1 1 0 1 1 0 1 1 0 1 ...
##  $ b8.3      : num  1 1 0 0 0 0 1 1 0 1 ...
##  $ b9.1      : num  1 1 1 0 1 1 0 1 1 1 ...
##  $ b9.2      : num  1 0 1 0 1 1 0 1 1 0 ...
##  $ b10       : num  1 1 1 1 0 1 0 1 0 0 ...
##  $ b11       : num  0 0 1 0 0 0 0 1 1 1 ...
##  $ b12       : num  1 1 0 1 1 0 0 1 0 1 ...
##  $ b13       : num  1 0 0 0 1 1 0 0 0 0 ...
##  $ b14       : num  3 0 3 0 0 0 0 3 0 0 ...
##  $ b15       : num  2 2 2 0 1 0 0 2 1 0 ...
##  $ b16       : num  0 0 2 0 0 2 0 2 2 2 ...
##  $ b17       : num  2 2 0 2 0 2 0 2 0 2 ...
##  $ b18       : num  0 0 0 2 0 0 0 2 0 2 ...
##  $ b19       : num  2 0 2 0 2 2 0 2 2 2 ...
##  $ b20       : num  0 0 2 2 0 0 0 2 0 2 ...
##  $ b21       : num  2 2 0 2 2 2 2 2 0 2 ...
##  $ b22       : num  2 2 0 2 0 2 0 2 0 2 ...
##  $ b23       : num  0 0 2 2 2 0 2 2 2 2 ...
##  $ b24       : num  0 0 2 2 0 2 0 0 0 0 ...
##  $ b25       : num  2 4 3 4 3 4 0 4 0 4 ...
##  $ b26       : num  1 3 3 3 1 3 2 3 0 3 ...
##  $ Total     : num  31 30 33 28 26 23 15 45 18 39 ...
##  $ IRTscore  : num  0.34288 0.29599 -0.00592 -0.1457 -0.08577 ...
##  $ IRTscoreSE: num  0.266 0.263 0.247 0.242 0.244 ...</code></pre>
</details>
<details>
<summary>
<p><code>summary(CZmaturaS)</code></p>
</summary>
<pre><code>##     SchType       FirstAtt       SchTypeGY            o1               o2              o3.1             o3.2             o4              o5              o6               o7       
##  GY4    :451   Min.   :0.000   Min.   :0.0000   Min.   :0.0000   Min.   :0.0000   Min.   :0.0000   Min.   :0.000   Min.   :0.000   Min.   :0.000   Min.   :0.0000   Min.   :0.000  
##  ST1    :432   1st Qu.:1.000   1st Qu.:0.0000   1st Qu.:0.0000   1st Qu.:0.0000   1st Qu.:0.0000   1st Qu.:0.000   1st Qu.:2.000   1st Qu.:1.000   1st Qu.:1.0000   1st Qu.:1.000  
##  GY8    :343   Median :1.000   Median :0.0000   Median :1.0000   Median :1.0000   Median :0.0000   Median :0.000   Median :2.000   Median :2.000   Median :1.0000   Median :2.000  
##  NOS    :152   Mean   :0.866   Mean   :0.4205   Mean   :0.6334   Mean   :0.6141   Mean   :0.3865   Mean   :0.227   Mean   :1.657   Mean   :1.415   Mean   :0.8078   Mean   :1.541  
##  UTE    :121   3rd Qu.:1.000   3rd Qu.:1.0000   3rd Qu.:1.0000   3rd Qu.:1.0000   3rd Qu.:1.0000   3rd Qu.:0.000   3rd Qu.:2.000   3rd Qu.:2.000   3rd Qu.:1.0000   3rd Qu.:2.000  
##  LYC    : 83   Max.   :1.000   Max.   :1.0000   Max.   :1.0000   Max.   :1.0000   Max.   :1.0000   Max.   :1.000   Max.   :2.000   Max.   :2.000   Max.   :1.0000   Max.   :2.000  
##  (Other):418                                    NA&#39;s   :88       NA&#39;s   :204      NA&#39;s   :828      NA&#39;s   :828     NA&#39;s   :128     NA&#39;s   :214     NA&#39;s   :314      NA&#39;s   :375    
##       o8.1             o8.2             o8.3             o9.1             o9.2             o10              o11              o12              o13              o14             o15       
##  Min.   :0.0000   Min.   :0.0000   Min.   :0.0000   Min.   :0.0000   Min.   :0.0000   Min.   :0.0000   Min.   :0.0000   Min.   :0.0000   Min.   :0.0000   Min.   :0.000   Min.   :0.000  
##  1st Qu.:1.0000   1st Qu.:1.0000   1st Qu.:0.0000   1st Qu.:1.0000   1st Qu.:0.0000   1st Qu.:0.0000   1st Qu.:0.0000   1st Qu.:0.0000   1st Qu.:0.0000   1st Qu.:0.000   1st Qu.:0.000  
##  Median :1.0000   Median :1.0000   Median :1.0000   Median :1.0000   Median :1.0000   Median :1.0000   Median :0.0000   Median :1.0000   Median :0.0000   Median :3.000   Median :2.000  
##  Mean   :0.8779   Mean   :0.7895   Mean   :0.6093   Mean   :0.8468   Mean   :0.6518   Mean   :0.7378   Mean   :0.4947   Mean   :0.6295   Mean   :0.4373   Mean   :1.667   Mean   :1.208  
##  3rd Qu.:1.0000   3rd Qu.:1.0000   3rd Qu.:1.0000   3rd Qu.:1.0000   3rd Qu.:1.0000   3rd Qu.:1.0000   3rd Qu.:1.0000   3rd Qu.:1.0000   3rd Qu.:1.0000   3rd Qu.:3.000   3rd Qu.:2.000  
##  Max.   :1.0000   Max.   :1.0000   Max.   :1.0000   Max.   :1.0000   Max.   :1.0000   Max.   :1.0000   Max.   :1.0000   Max.   :1.0000   Max.   :1.0000   Max.   :3.000   Max.   :2.000  
##  NA&#39;s   :280      NA&#39;s   :280      NA&#39;s   :280      NA&#39;s   :179      NA&#39;s   :179      NA&#39;s   :234      NA&#39;s   :387      NA&#39;s   :178      NA&#39;s   :150      NA&#39;s   :671     NA&#39;s   :408    
##      o16.1           o16.2           o16.3           o16.4            o17             o18             o19             o20             o21             o22            o23             o24       
##  Min.   :1.000   Min.   :1.000   Min.   :1.000   Min.   :1.000   Min.   :1.000   Min.   :1.000   Min.   :1.000   Min.   :1.000   Min.   :1.000   Min.   :1.00   Min.   :1.000   Min.   :1.000  
##  1st Qu.:1.000   1st Qu.:1.000   1st Qu.:1.000   1st Qu.:1.000   1st Qu.:3.000   1st Qu.:2.000   1st Qu.:2.000   1st Qu.:1.000   1st Qu.:3.000   1st Qu.:1.00   1st Qu.:3.000   1st Qu.:2.000  
##  Median :1.000   Median :1.000   Median :1.000   Median :1.000   Median :4.000   Median :2.000   Median :4.000   Median :3.000   Median :4.000   Median :1.00   Median :5.000   Median :3.000  
##  Mean   :1.433   Mean   :1.296   Mean   :1.313   Mean   :1.327   Mean   :3.496   Mean   :2.458   Mean   :3.066   Mean   :2.683   Mean   :3.577   Mean   :2.02   Mean   :3.913   Mean   :2.774  
##  3rd Qu.:2.000   3rd Qu.:2.000   3rd Qu.:2.000   3rd Qu.:2.000   3rd Qu.:4.000   3rd Qu.:3.000   3rd Qu.:4.000   3rd Qu.:4.000   3rd Qu.:4.000   3rd Qu.:3.00   3rd Qu.:5.000   3rd Qu.:3.000  
##  Max.   :2.000   Max.   :2.000   Max.   :2.000   Max.   :2.000   Max.   :5.000   Max.   :5.000   Max.   :5.000   Max.   :5.000   Max.   :5.000   Max.   :5.00   Max.   :5.000   Max.   :5.000  
##  NA&#39;s   :29      NA&#39;s   :45      NA&#39;s   :47      NA&#39;s   :54      NA&#39;s   :15      NA&#39;s   :46      NA&#39;s   :37      NA&#39;s   :64      NA&#39;s   :48      NA&#39;s   :55     NA&#39;s   :19      NA&#39;s   :31     
##      o25.1           o25.2           o25.3           o25.4           o26.1           o26.2             b1               b2              b3.1             b3.2             b4             b5       
##  Min.   :1.000   Min.   :1.000   Min.   :1.000   Min.   :1.000   Min.   :1.000   Min.   :1.000   Min.   :0.0000   Min.   :0.0000   Min.   :0.0000   Min.   :0.000   Min.   :0.00   Min.   :0.000  
##  1st Qu.:3.000   1st Qu.:6.000   1st Qu.:1.000   1st Qu.:2.000   1st Qu.:5.000   1st Qu.:3.000   1st Qu.:0.0000   1st Qu.:0.0000   1st Qu.:0.0000   1st Qu.:0.000   1st Qu.:2.00   1st Qu.:0.000  
##  Median :3.000   Median :6.000   Median :1.000   Median :2.000   Median :5.000   Median :3.000   Median :1.0000   Median :1.0000   Median :0.0000   Median :0.000   Median :2.00   Median :2.000  
##  Mean   :3.115   Mean   :5.431   Mean   :1.884   Mean   :2.407   Mean   :4.565   Mean   :2.873   Mean   :0.6055   Mean   :0.5515   Mean   :0.2265   Mean   :0.133   Mean   :1.55   Mean   :1.264  
##  3rd Qu.:3.000   3rd Qu.:6.000   3rd Qu.:2.000   3rd Qu.:3.000   3rd Qu.:5.000   3rd Qu.:3.000   3rd Qu.:1.0000   3rd Qu.:1.0000   3rd Qu.:0.0000   3rd Qu.:0.000   3rd Qu.:2.00   3rd Qu.:2.000  
##  Max.   :6.000   Max.   :6.000   Max.   :6.000   Max.   :6.000   Max.   :5.000   Max.   :5.000   Max.   :1.0000   Max.   :1.0000   Max.   :1.0000   Max.   :1.000   Max.   :2.00   Max.   :2.000  
##  NA&#39;s   :40      NA&#39;s   :45      NA&#39;s   :55      NA&#39;s   :75      NA&#39;s   :17      NA&#39;s   :24                                                                                                       
##        b6              b7             b8.1            b8.2            b8.3            b9.1            b9.2             b10              b11             b12              b13        
##  Min.   :0.000   Min.   :0.000   Min.   :0.000   Min.   :0.000   Min.   :0.000   Min.   :0.000   Min.   :0.0000   Min.   :0.0000   Min.   :0.000   Min.   :0.0000   Min.   :0.0000  
##  1st Qu.:0.000   1st Qu.:0.000   1st Qu.:1.000   1st Qu.:0.000   1st Qu.:0.000   1st Qu.:1.000   1st Qu.:0.0000   1st Qu.:0.0000   1st Qu.:0.000   1st Qu.:0.0000   1st Qu.:0.0000  
##  Median :1.000   Median :2.000   Median :1.000   Median :1.000   Median :1.000   Median :1.000   Median :1.0000   Median :1.0000   Median :0.000   Median :1.0000   Median :0.0000  
##  Mean   :0.681   Mean   :1.252   Mean   :0.755   Mean   :0.679   Mean   :0.524   Mean   :0.771   Mean   :0.5935   Mean   :0.6515   Mean   :0.399   Mean   :0.5735   Mean   :0.4045  
##  3rd Qu.:1.000   3rd Qu.:2.000   3rd Qu.:1.000   3rd Qu.:1.000   3rd Qu.:1.000   3rd Qu.:1.000   3rd Qu.:1.0000   3rd Qu.:1.0000   3rd Qu.:1.000   3rd Qu.:1.0000   3rd Qu.:1.0000  
##  Max.   :1.000   Max.   :2.000   Max.   :1.000   Max.   :1.000   Max.   :1.000   Max.   :1.000   Max.   :1.0000   Max.   :1.0000   Max.   :1.000   Max.   :1.0000   Max.   :1.0000  
##                                                                                                                                                                                     
##       b14             b15             b16              b17             b18             b19             b20             b21             b22             b23             b24             b25      
##  Min.   :0.000   Min.   :0.000   Min.   :0.0000   Min.   :0.000   Min.   :0.000   Min.   :0.000   Min.   :0.000   Min.   :0.000   Min.   :0.000   Min.   :0.000   Min.   :0.000   Min.   :0.00  
##  1st Qu.:0.000   1st Qu.:0.000   1st Qu.:0.0000   1st Qu.:0.000   1st Qu.:0.000   1st Qu.:0.000   1st Qu.:0.000   1st Qu.:0.000   1st Qu.:0.000   1st Qu.:0.000   1st Qu.:0.000   1st Qu.:1.00  
##  Median :0.000   Median :1.000   Median :1.0000   Median :2.000   Median :2.000   Median :0.000   Median :0.000   Median :2.000   Median :2.000   Median :2.000   Median :0.000   Median :3.00  
##  Mean   :1.108   Mean   :0.962   Mean   :0.8435   Mean   :1.128   Mean   :1.207   Mean   :0.995   Mean   :0.693   Mean   :1.242   Mean   :1.205   Mean   :1.094   Mean   :0.787   Mean   :2.59  
##  3rd Qu.:3.000   3rd Qu.:2.000   3rd Qu.:2.0000   3rd Qu.:2.000   3rd Qu.:2.000   3rd Qu.:2.000   3rd Qu.:2.000   3rd Qu.:2.000   3rd Qu.:2.000   3rd Qu.:2.000   3rd Qu.:2.000   3rd Qu.:4.00  
##  Max.   :3.000   Max.   :2.000   Max.   :2.0000   Max.   :2.000   Max.   :2.000   Max.   :2.000   Max.   :2.000   Max.   :2.000   Max.   :2.000   Max.   :2.000   Max.   :2.000   Max.   :4.00  
##                                                                                                                                                                                                 
##       b26            Total          IRTscore          IRTscoreSE    
##  Min.   :0.000   Min.   : 1.00   Min.   :-2.51891   Min.   :0.2396  
##  1st Qu.:1.000   1st Qu.:18.00   1st Qu.:-0.66107   1st Qu.:0.2458  
##  Median :2.000   Median :28.00   Median :-0.04423   Median :0.2665  
##  Mean   :2.126   Mean   :27.59   Mean   :-0.01308   Mean   :0.2895  
##  3rd Qu.:3.000   3rd Qu.:37.00   3rd Qu.: 0.60386   3rd Qu.:0.3103  
##  Max.   :3.000   Max.   :50.00   Max.   : 2.31246   Max.   :0.5404  
## </code></pre>
</details>
<p></br></p>
<p>The CZmaturaS dataset contains a sample of 2000 students’ results from the czech matura exam in Mathematics. The dataset consists of 2000 rows and 73 columns. The code of the given school type is stored in the variable <code>SchType</code>, a factor variable with 16 levels. <code>FirstAtt</code> provides information about whether it was the student’s first attempt at the exam or not. It is set to a numeric variable, although it only takes on two values (binary). As can be deduced from the <code>summary()</code> function’s output, approximately 87 % students in this dataset were taking the exam for the first time. <code>SchTypeGY</code> was computed from the <code>SchType</code> variable, ascribing value ‘1’ to all schools of type <code>gymnázium</code> and value ‘0’ to all other school types (binary). It is also set to a numeric variable. The <code>summary()</code> function’s output tells us, that circa 42 % of students in this sample were attending a <em>gymnázium</em>. Columns <code>o1</code>–<code>o26.2</code> contain item answers, columns <code>b1</code>–<code>b26</code> represent scored item answers. <code>Total</code> stands for total score and was computed as the sum of item scores for each student. <code>Total</code> spans the range 1 to 50 with a mean score of 27.59 and a median score of 28. </br></p>
</div>
<div id="b.-provide-descriptive-statistics-and-plots-for-all-relevant-variables.-are-the-total-scores-approximately-normally-distributed-whywhy-not" class="section level5">
<h5>4b. Provide descriptive statistics and plots for all relevant variables. Are the total scores approximately normally distributed? Why/Why not?</h5>
<pre class="r"><code>#Descriptive statistics of total scores
describe(CZmaturaS$Total, na.rm = FALSE)</code></pre>
<pre><code>##    vars    n  mean    sd median trimmed   mad min max range  skew kurtosis   se
## X1    1 2000 27.59 11.95     28   27.73 13.34   1  50    49 -0.09    -0.93 0.27</code></pre>
<pre class="r"><code>#Descriptive statistics of total scores grouped by &#39;SchTypeGY&#39;
describeBy(CZmaturaS[, c(&quot;SchTypeGY&quot;, &quot;Total&quot;)], group = &quot;SchTypeGY&quot;)</code></pre>
<pre><code>## 
##  Descriptive statistics by group 
## SchTypeGY: 0
##           vars    n  mean    sd median trimmed   mad min max range skew kurtosis   se
## SchTypeGY    1 1159  0.00  0.00      0    0.00  0.00   0   0     0  NaN      NaN 0.00
## Total        2 1159 22.13 10.67     21   21.77 11.86   1  50    49 0.25    -0.75 0.31
## -------------------------------------------------------------------------------------------------------------------------------------------------- 
## SchTypeGY: 1
##           vars   n  mean   sd median trimmed   mad min max range  skew kurtosis   se
## SchTypeGY    1 841  1.00 0.00      1    1.00  0.00   1   1     0   NaN      NaN 0.00
## Total        2 841 35.12 9.24     35   35.62 10.38   5  50    45 -0.42    -0.47 0.32</code></pre>
<pre class="r"><code>#Histogram of total scores
ggplot(CZmaturaS, aes(Total)) +
  geom_histogram(binwidth = 1, fill = &quot;#69b3a2&quot;, col=&quot;#e9ecef&quot;) +
        xlab(&quot;Total score&quot;) +
        ylab(&quot;Number of respondents&quot;) +
        theme_bw()</code></pre>
<p><img src="HW1_files/figure-html/compute_total_scores-1.png" width="672" /></p>
<pre class="r"><code>#Q-Q plot of total scores
ggpubr::ggqqplot(CZmaturaS$Total, ylim=c(0,50), col =&quot;#69b3a2&quot;) +
  theme_bw()</code></pre>
<p><img src="HW1_files/figure-html/compute_total_scores-2.png" width="672" /></p>
<pre class="r"><code>#Histogram of total scores grouped by &#39;SchTypeGY&#39;
ggplot(CZmaturaS, aes(x=Total, fill=(as.factor(SchTypeGY)))) +
    geom_histogram(color=&quot;#e9ecef&quot;, 
                   alpha=0.6, 
                   position = &#39;identity&#39;, 
                   binwidth = 1) +
    scale_fill_manual(values=c(&quot;#69b3a2&quot;, &quot;#404080&quot;), 
                      name = &quot;School type&quot;, 
                      labels = c(&quot;Other&quot;, &quot;Gymnázium&quot;)) +
    theme_bw()</code></pre>
<p><img src="HW1_files/figure-html/compute_total_scores-3.png" width="672" /></p>
<pre class="r"><code>#Descriptive statistics of total scores grouped by &#39;FirstAtt&#39;
describeBy(CZmaturaS[, c(&quot;FirstAtt&quot;, &quot;Total&quot;)], group = &quot;FirstAtt&quot;)</code></pre>
<pre><code>## 
##  Descriptive statistics by group 
## FirstAtt: 0
##          vars   n mean   sd median trimmed  mad min max range skew kurtosis   se
## FirstAtt    1 268  0.0 0.00      0    0.00 0.00   0   0     0  NaN      NaN 0.00
## Total       2 268 16.9 8.94     16   16.31 9.64   2  43    41 0.58    -0.13 0.55
## -------------------------------------------------------------------------------------------------------------------------------------------------- 
## FirstAtt: 1
##          vars    n  mean   sd median trimmed   mad min max range skew kurtosis   se
## FirstAtt    1 1732  1.00  0.0      1    1.00  0.00   1   1     0  NaN      NaN 0.00
## Total       2 1732 29.25 11.5     30   29.55 13.34   1  50    49 -0.2    -0.81 0.28</code></pre>
<pre class="r"><code>#Histogram of total scores grouped by &#39;FirstAtt&#39;
ggplot(CZmaturaS, aes(x=Total, fill=(as.factor(FirstAtt)))) +
    geom_histogram(color=&quot;#e9ecef&quot;, 
                   alpha=0.6, 
                   position = &#39;identity&#39;, 
                   binwidth = 1) +
    scale_fill_manual(values=c(&quot;#404080&quot;, &quot;#69b3a2&quot;), name = &quot;First attempt&quot;, labels = c(&quot;No&quot;, &quot;Yes&quot;)) +
    theme_bw()</code></pre>
<p><img src="HW1_files/figure-html/unnamed-chunk-17-1.png" width="672" /></p>
<p>The total scores do not follow a normal distribution. The median (28) is larger than the mean (27.59) which suggests a slight negative skew (-0.09). The kurtosis is negative as well (-0.93), thus pointing to a somewhat platykurtic distribution. Although the histogram of total scores does not seem obviously non-normal, the Q-Q plot shows a clear deviance from the normal distribution around the tails. After plotting a separate histogram for schools of type <em>gymnázium</em>, it becomes apparent that the underlying distribution is not unimodal <em>Gymnázium</em> students are, on average, more successful (mean total score of 35.12) than other students (mean total score of 22.13). The distribution of the <em>gymnázium</em> students’ total scores has a negative skew (-0.42), whereas the distribution of other students’ total scores is positively-skewed (0.25). Similarly, the distributions of total scores differ when the variable <code>FirstAtt</code> is considered. The sample of students who are repeating the exam is quite small (n = 268). Nonetheless, their average total score (16.9) is distinctly lower than the total score of students who are taking the exam for the first time (29.25), and the distribution of their scores is positively skewed (0.58). </br></p>
</div>
<div id="c-compute-the-z-scores-t-scores-percentiles-and-success-rate-for-all-respondents.-interpret-the-results-for-the-first-respondent." class="section level5">
<h5>4c Compute the Z-scores, T-scores, percentiles, and success rate for all respondents. Interpret the results for the first respondent.</h5>
<pre class="r"><code>zscore &lt;- scale(CZmaturaS$Total)
tscore &lt;- 10 * zscore + 50
ecdf &lt;- ecdf(CZmaturaS$Total)
percentiles &lt;- as.matrix(100 * round(ecdf(CZmaturaS$Total), 2))
success_rate &lt;- as.matrix(100 * (CZmaturaS$Total / max(CZmaturaS$Total)))
data.frame(zscore[1,], tscore[1,], percentiles[1,], success_rate[1,])</code></pre>
<pre><code>##   zscore.1... tscore.1... percentiles.1... success_rate.1...
## 1   0.2848704     52.8487               60                62</code></pre>
<p>The first respondent has a Z-score of circa 0.28, which means their total score lies 0.28 times the standard deviation above the mean of this sample (Z-score = 0). The T-score of this student is approximately 52.85 which again points to an above-average (50) result. Their percentile is 60, meaning 60 % of respondents in this sample scored less than or equal to the first respondent. The respondent’s success rate is 62, which means their total score corresponds to 62 % of the best total score in this sample (50).</p>
<p></br></p>
</div>
<div id="d-work-with-shinyitemanalysis-interactive-app-locally-or-online-at-httpsshiny.cs.cas.czshinyitemanalysis-or-httpscemp.shinyapps.ioshinyitemanalysis.-upload-the-czmaturas.csv-data-files-into-the-interactive-app-and-explore-the-different-tabs-of-the-app.-download-attach-and-interpret-the-3-color-histogram-of-the-summary-scores." class="section level5">
<h5>4d Work with ShinyItemAnalysis interactive app locally or online at <a href="https://shiny.cs.cas.cz/ShinyItemAnalysis/" class="uri">https://shiny.cs.cas.cz/ShinyItemAnalysis/</a> or <a href="https://cemp.shinyapps.io/ShinyItemAnalysis/" class="uri">https://cemp.shinyapps.io/ShinyItemAnalysis/</a>. Upload the <code>CZmaturaS.csv</code> data files into the interactive app and explore the different tabs of the app. Download, attach and interpret the 3-color histogram of the summary scores.</h5>
<pre class="r"><code># colors by cut-score
cut &lt;- median(CZmaturaS$Total) # cut-score
color &lt;- c(rep(&quot;red&quot;, cut - min(CZmaturaS$Total)), &quot;gray&quot;, rep(&quot;blue&quot;, max(CZmaturaS$Total) - cut))
df &lt;- data.frame(CZmaturaS$Total)

# 3-color histogram
ggplot(df, aes(CZmaturaS.Total)) +
  geom_histogram(binwidth = 1, fill = color, col = &quot;black&quot;) +
  xlab(&quot;Total score&quot;) +
  ylab(&quot;Number of respondents&quot;) +
  theme_bw()</code></pre>
<p><img src="HW1_files/figure-html/work%20with%20SIA-1.png" width="672" /></p>
<p>The 3-color histogram depicts the total scores with a cut-score – in this case, the median (28). The cut-score is represented by the grey column, which divides the sample into two equally sized groups. Students who scored below the median of this sample are red, students who scored above the sample median are blue. Lastly, students who reached a total score equal to the median are shown in the grey column.</p>
<p></br></p>
</div>
</div>
<div id="provide-constructive-feedback-to-the-lecture-exercises-or-any-of-the-material.-which-dataset-would-you-like-to-analyze-for-the-project-bonus-1-pt" class="section level4">
<h4>5. Provide constructive feedback to the lecture, exercises, or any of the material. Which dataset would you like to analyze for the project? [BONUS 1 pt]</h4>
<p>I find the lectures to be very helpful, I especially appreciate how well prepared the study materials are (e.g. the online R tutorial). I also think there’s a very good balance of theory (lectures, reading materials) and praxis.</p>
<p></br></p>
</div>




</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.odd').parent('tbody').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- tabsets -->

<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});

$(document).ready(function () {
  $('.tabset-dropdown > .nav-tabs > li').click(function () {
    $(this).parent().toggleClass('nav-tabs-open');
  });
});
</script>

<!-- code folding -->


<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
