<!DOCTYPE html>

<html>

<head>

<meta charset="utf-8" />
<meta name="generator" content="pandoc" />
<meta http-equiv="X-UA-Compatible" content="IE=EDGE" />


<meta name="author" content="Kateřina Hudáčová (Benjamín Kunc)" />


<title>Selected Topics of Psychometrics (NMST570)</title>

<script src="site_libs/header-attrs-2.11/header-attrs.js"></script>
<script src="site_libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="site_libs/bootstrap-3.3.5/css/cerulean.min.css" rel="stylesheet" />
<script src="site_libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<style>h1 {font-size: 34px;}
       h1.title {font-size: 38px;}
       h2 {font-size: 30px;}
       h3 {font-size: 24px;}
       h4 {font-size: 18px;}
       h5 {font-size: 16px;}
       h6 {font-size: 12px;}
       code {color: inherit; background-color: rgba(0, 0, 0, 0.04);}
       pre:not([class]) { background-color: white }</style>
<script src="site_libs/jqueryui-1.11.4/jquery-ui.min.js"></script>
<link href="site_libs/tocify-1.9.1/jquery.tocify.css" rel="stylesheet" />
<script src="site_libs/tocify-1.9.1/jquery.tocify.js"></script>
<script src="site_libs/navigation-1.1/tabsets.js"></script>
<script src="site_libs/navigation-1.1/codefolding.js"></script>
<link href="site_libs/highlightjs-9.12.0/default.css" rel="stylesheet" />
<script src="site_libs/highlightjs-9.12.0/highlight.js"></script>
<link href="site_libs/pagedtable-1.1/css/pagedtable.css" rel="stylesheet" />
<script src="site_libs/pagedtable-1.1/js/pagedtable.js"></script>

<style type="text/css">
  code{white-space: pre-wrap;}
  span.smallcaps{font-variant: small-caps;}
  span.underline{text-decoration: underline;}
  div.column{display: inline-block; vertical-align: top; width: 50%;}
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
  ul.task-list{list-style: none;}
    </style>

<style type="text/css">code{white-space: pre;}</style>
<script type="text/javascript">
if (window.hljs) {
  hljs.configure({languages: []});
  hljs.initHighlightingOnLoad();
  if (document.readyState && document.readyState === "complete") {
    window.setTimeout(function() { hljs.initHighlighting(); }, 0);
  }
}
</script>








<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
img {
  max-width:100%;
}
.tabbed-pane {
  padding-top: 12px;
}
.html-widget {
  margin-bottom: 20px;
}
button.code-folding-btn:focus {
  outline: none;
}
summary {
  display: list-item;
}
pre code {
  padding: 0;
}
</style>


<style type="text/css">
.dropdown-submenu {
  position: relative;
}
.dropdown-submenu>.dropdown-menu {
  top: 0;
  left: 100%;
  margin-top: -6px;
  margin-left: -1px;
  border-radius: 0 6px 6px 6px;
}
.dropdown-submenu:hover>.dropdown-menu {
  display: block;
}
.dropdown-submenu>a:after {
  display: block;
  content: " ";
  float: right;
  width: 0;
  height: 0;
  border-color: transparent;
  border-style: solid;
  border-width: 5px 0 5px 5px;
  border-left-color: #cccccc;
  margin-top: 5px;
  margin-right: -10px;
}
.dropdown-submenu:hover>a:after {
  border-left-color: #adb5bd;
}
.dropdown-submenu.pull-left {
  float: none;
}
.dropdown-submenu.pull-left>.dropdown-menu {
  left: -100%;
  margin-left: 10px;
  border-radius: 6px 0 6px 6px;
}
</style>

<script type="text/javascript">
// manage active state of menu based on current page
$(document).ready(function () {
  // active menu anchor
  href = window.location.pathname
  href = href.substr(href.lastIndexOf('/') + 1)
  if (href === "")
    href = "index.html";
  var menuAnchor = $('a[href="' + href + '"]');

  // mark it active
  menuAnchor.tab('show');

  // if it's got a parent navbar menu mark it active as well
  menuAnchor.closest('li.dropdown').addClass('active');

  // Navbar adjustments
  var navHeight = $(".navbar").first().height() + 15;
  var style = document.createElement('style');
  var pt = "padding-top: " + navHeight + "px; ";
  var mt = "margin-top: -" + navHeight + "px; ";
  var css = "";
  // offset scroll position for anchor links (for fixed navbar)
  for (var i = 1; i <= 6; i++) {
    css += ".section h" + i + "{ " + pt + mt + "}\n";
  }
  style.innerHTML = "body {" + pt + "padding-bottom: 40px; }\n" + css;
  document.head.appendChild(style);
});
</script>

<!-- tabsets -->

<style type="text/css">
.tabset-dropdown > .nav-tabs {
  display: inline-table;
  max-height: 500px;
  min-height: 44px;
  overflow-y: auto;
  border: 1px solid #ddd;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs > li.active:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li.active:before {
  content: "&#xe258;";
  border: none;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs > li.active {
  display: block;
}

.tabset-dropdown > .nav-tabs > li > a,
.tabset-dropdown > .nav-tabs > li > a:focus,
.tabset-dropdown > .nav-tabs > li > a:hover {
  border: none;
  display: inline-block;
  border-radius: 4px;
  background-color: transparent;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li {
  display: block;
  float: none;
}

.tabset-dropdown > .nav-tabs > li {
  display: none;
}
</style>

<!-- code folding -->
<style type="text/css">
.code-folding-btn { margin-bottom: 4px; }
</style>



<style type="text/css">

#TOC {
  margin: 25px 0px 20px 0px;
}
@media (max-width: 768px) {
#TOC {
  position: relative;
  width: 100%;
}
}

@media print {
.toc-content {
  /* see https://github.com/w3c/csswg-drafts/issues/4434 */
  float: right;
}
}

.toc-content {
  padding-left: 30px;
  padding-right: 40px;
}

div.main-container {
  max-width: 1200px;
}

div.tocify {
  width: 20%;
  max-width: 260px;
  max-height: 85%;
}

@media (min-width: 768px) and (max-width: 991px) {
  div.tocify {
    width: 25%;
  }
}

@media (max-width: 767px) {
  div.tocify {
    width: 100%;
    max-width: none;
  }
}

.tocify ul, .tocify li {
  line-height: 20px;
}

.tocify-subheader .tocify-item {
  font-size: 0.90em;
}

.tocify .list-group-item {
  border-radius: 0px;
}


</style>



</head>

<body>


<div class="container-fluid main-container">


<!-- setup 3col/9col grid for toc_float and main content  -->
<div class="row">
<div class="col-xs-12 col-sm-4 col-md-3">
<div id="TOC" class="tocify">
</div>
</div>

<div class="toc-content col-xs-12 col-sm-8 col-md-9">




<div class="navbar navbar-default  navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="index.html">Psychometrics</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li>
  <a href="index.html">HW1</a>
</li>
<li>
  <a href="HW2.html">HW2</a>
</li>
<li>
  <a href="HW3.html">HW3</a>
</li>
<li>
  <a href="HW4.html">HW4</a>
</li>
<li>
  <a href="HW5.html">HW5</a>
</li>
<li>
  <a href="HW6.html">HW6</a>
</li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container -->
</div><!--/.navbar -->

<div id="header">

<div class="btn-group pull-right float-right">
<button type="button" class="btn btn-default btn-xs btn-secondary btn-sm dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><span>Code</span> <span class="caret"></span></button>
<ul class="dropdown-menu dropdown-menu-right" style="min-width: 50px;">
<li><a id="rmd-show-all-code" href="#">Show All Code</a></li>
<li><a id="rmd-hide-all-code" href="#">Hide All Code</a></li>
</ul>
</div>



<h1 class="title toc-ignore">Selected Topics of Psychometrics (NMST570)</h1>
<h3 class="subtitle">Homework Assignment 2: Validity</h3>
<h4 class="author">Kateřina Hudáčová (Benjamín Kunc)</h4>

</div>


<p>Note: The assignment is due on Oct 25, 2021. Send your code and html/pdf report to <code>dlouha@cs.cas.cz</code> (and to <code>martinkova@cs.cas.cz</code> in copy).</p>
<p></br></p>
<div id="read-and-comment-on-chapter-2-on-httpsperusall.com.-2-pts" class="section level4">
<h4>1. Read and comment on Chapter 2 on <a href="https://perusall.com" class="uri">https://perusall.com</a>. [2 pts]</h4>
<p>Done.</p>
</div>
<div id="run-the-code-for-the-chapter-2-available-on-course-webpage-httpwww.cs.cas.czmartinkovanmst570.html." class="section level4">
<h4>2. Run the code for the Chapter 2, available on course webpage <a href="http://www.cs.cas.cz/martinkova/NMST570.html" class="uri">http://www.cs.cas.cz/martinkova/NMST570.html</a>.</h4>
<p>Done.</p>
</div>
<div id="complete-the-caplearnr-online-tutorial-for-validity.-attach-certificate.-4-pts" class="section level4">
<h4>3. Complete the CAPlearnR online tutorial for Validity. Attach certificate. [4 pts]</h4>
<blockquote>
<p>Note: If you meet any issues, contact the the TA or the instructor before 8 AM of the due date.</p>
</blockquote>
<p>Done.</p>
</div>
<div id="project-preparation-explore-the-czech-matura-data-or-data-of-your-choice-as-described-below.-you-can-work-with-1-2-teammates-on-this-task.-all-teammate-names-have-to-be-included-on-your-answer-sheet.-4-pts" class="section level4">
<h4>4. Project preparation: Explore the Czech matura data OR DATA OF YOUR CHOICE as described below. You can work with 1-2 teammates on this task. All teammate names have to be included on your answer sheet. [4 pts]</h4>
<div id="a.-the-original-czech-matura-data-is-available-on-httpsvysledky.cermat.czstatistika.-you-need-to-select-maturitní-zkoušky-jaro---2019-and-click-on-matematika-at-the-very-botom-in-the-neagregovaná-položková-data-section.-this-will-download-a-.xls-file-with-the-item-data.-you-may-view-the-file-and-its-decription-which-is-avalable-on-the-webpage.-load-the-data-and-prepare-it-for-the-analysis.-check-item-wording-include-the-link-where-it-can-be-found." class="section level5">
<h5>4a. The original Czech matura data is available on <a href="https://vysledky.cermat.cz/statistika/" class="uri">https://vysledky.cermat.cz/statistika/</a>. You need to select <code>Maturitní zkoušky</code> <code>Jaro - 2019</code> and click on <code>Matematika</code> at the very botom in the <code>Neagregovaná položková data</code> section. This will download a .xls file with the item data. You may view the file and its decription which is avalable on the webpage. Load the data and prepare it for the analysis. Check item wording (include the link where it can be found).</h5>
<pre class="r"><code># read data
data(BFI2, package=&#39;ShinyItemAnalysis&#39;)</code></pre>
<details>
<summary>
<code>summary()</code>
</summary>
<pre class="r"><code>summary(BFI2)</code></pre>
<pre><code>##        i1             i2              i3              i4              i5              i6              i7              i8              i9            i10             i11             i12       
##  Min.   :1.00   Min.   :1.000   Min.   :1.000   Min.   :1.000   Min.   :1.000   Min.   :1.000   Min.   :1.000   Min.   :1.000   Min.   :1.00   Min.   :1.000   Min.   :1.000   Min.   :1.000  
##  1st Qu.:3.00   1st Qu.:4.000   1st Qu.:2.000   1st Qu.:2.000   1st Qu.:2.000   1st Qu.:3.000   1st Qu.:4.000   1st Qu.:1.000   1st Qu.:2.00   1st Qu.:3.000   1st Qu.:3.000   1st Qu.:2.000  
##  Median :4.00   Median :4.000   Median :3.000   Median :3.000   Median :3.000   Median :4.000   Median :4.000   Median :2.000   Median :3.00   Median :4.000   Median :4.000   Median :3.000  
##  Mean   :3.62   Mean   :4.102   Mean   :3.053   Mean   :3.063   Mean   :3.213   Mean   :3.591   Mean   :4.051   Mean   :2.344   Mean   :2.68   Mean   :3.939   Mean   :3.641   Mean   :3.003  
##  3rd Qu.:4.00   3rd Qu.:5.000   3rd Qu.:4.000   3rd Qu.:4.000   3rd Qu.:4.000   3rd Qu.:4.000   3rd Qu.:5.000   3rd Qu.:3.000   3rd Qu.:4.00   3rd Qu.:5.000   3rd Qu.:4.000   3rd Qu.:4.000  
##  Max.   :5.00   Max.   :5.000   Max.   :5.000   Max.   :5.000   Max.   :5.000   Max.   :5.000   Max.   :5.000   Max.   :5.000   Max.   :5.00   Max.   :5.000   Max.   :5.000   Max.   :5.000  
##                                                                                                                                                                                               
##       i13             i14             i15             i16             i17             i18             i19             i20             i21            i22             i23             i24       
##  Min.   :1.000   Min.   :1.000   Min.   :1.000   Min.   :1.000   Min.   :1.000   Min.   :1.000   Min.   :1.000   Min.   :1.000   Min.   :1.00   Min.   :1.000   Min.   :1.000   Min.   :1.000  
##  1st Qu.:3.000   1st Qu.:2.000   1st Qu.:3.000   1st Qu.:2.000   1st Qu.:4.000   1st Qu.:2.000   1st Qu.:2.000   1st Qu.:2.000   1st Qu.:2.00   1st Qu.:3.000   1st Qu.:2.000   1st Qu.:2.000  
##  Median :4.000   Median :3.000   Median :4.000   Median :3.000   Median :4.000   Median :3.000   Median :3.000   Median :4.000   Median :3.00   Median :4.000   Median :3.000   Median :3.000  
##  Mean   :3.628   Mean   :3.017   Mean   :3.548   Mean   :2.939   Mean   :4.015   Mean   :3.317   Mean   :3.068   Mean   :3.395   Mean   :2.95   Mean   :3.988   Mean   :2.755   Mean   :2.889  
##  3rd Qu.:4.000   3rd Qu.:4.000   3rd Qu.:4.000   3rd Qu.:4.000   3rd Qu.:5.000   3rd Qu.:4.000   3rd Qu.:4.000   3rd Qu.:4.000   3rd Qu.:4.00   3rd Qu.:5.000   3rd Qu.:4.000   3rd Qu.:4.000  
##  Max.   :5.000   Max.   :5.000   Max.   :5.000   Max.   :5.000   Max.   :5.000   Max.   :5.000   Max.   :5.000   Max.   :5.000   Max.   :5.00   Max.   :5.000   Max.   :5.000   Max.   :5.000  
##                                                                                                                                                                                                
##       i25             i26            i27             i28             i29             i30             i31             i32             i33             i34             i35             i36     
##  Min.   :1.000   Min.   :1.00   Min.   :1.000   Min.   :1.000   Min.   :1.000   Min.   :1.000   Min.   :1.000   Min.   :1.000   Min.   :1.000   Min.   :1.000   Min.   :1.000   Min.   :1.0  
##  1st Qu.:3.000   1st Qu.:3.00   1st Qu.:3.000   1st Qu.:2.000   1st Qu.:2.000   1st Qu.:3.000   1st Qu.:2.000   1st Qu.:4.000   1st Qu.:2.000   1st Qu.:3.000   1st Qu.:3.000   1st Qu.:2.0  
##  Median :4.000   Median :3.00   Median :4.000   Median :3.000   Median :3.000   Median :4.000   Median :2.000   Median :4.000   Median :3.000   Median :4.000   Median :4.000   Median :3.0  
##  Mean   :3.556   Mean   :3.45   Mean   :3.813   Mean   :3.196   Mean   :2.973   Mean   :3.562   Mean   :2.707   Mean   :3.937   Mean   :3.199   Mean   :3.548   Mean   :3.733   Mean   :3.2  
##  3rd Qu.:5.000   3rd Qu.:4.00   3rd Qu.:5.000   3rd Qu.:4.000   3rd Qu.:4.000   3rd Qu.:4.000   3rd Qu.:4.000   3rd Qu.:4.000   3rd Qu.:4.000   3rd Qu.:4.000   3rd Qu.:5.000   3rd Qu.:4.0  
##  Max.   :5.000   Max.   :5.00   Max.   :5.000   Max.   :5.000   Max.   :5.000   Max.   :5.000   Max.   :5.000   Max.   :5.000   Max.   :5.000   Max.   :5.000   Max.   :5.000   Max.   :5.0  
##                                                                                                                                                                                              
##       i37             i38             i39             i40             i41             i42             i43             i44             i45             i46             i47             i48       
##  Min.   :1.000   Min.   :1.000   Min.   :1.000   Min.   :1.000   Min.   :1.000   Min.   :1.000   Min.   :1.000   Min.   :1.000   Min.   :1.000   Min.   :1.000   Min.   :1.000   Min.   :1.000  
##  1st Qu.:2.000   1st Qu.:3.000   1st Qu.:2.000   1st Qu.:4.000   1st Qu.:3.000   1st Qu.:2.000   1st Qu.:3.000   1st Qu.:2.000   1st Qu.:3.000   1st Qu.:3.000   1st Qu.:2.000   1st Qu.:2.000  
##  Median :3.000   Median :4.000   Median :3.000   Median :4.000   Median :4.000   Median :3.000   Median :4.000   Median :2.000   Median :4.000   Median :4.000   Median :4.000   Median :4.000  
##  Mean   :3.157   Mean   :3.578   Mean   :2.796   Mean   :4.002   Mean   :3.418   Mean   :2.829   Mean   :3.872   Mean   :2.684   Mean   :3.912   Mean   :3.533   Mean   :3.294   Mean   :3.342  
##  3rd Qu.:4.000   3rd Qu.:4.000   3rd Qu.:4.000   3rd Qu.:5.000   3rd Qu.:4.000   3rd Qu.:4.000   3rd Qu.:4.000   3rd Qu.:4.000   3rd Qu.:5.000   3rd Qu.:4.000   3rd Qu.:4.000   3rd Qu.:4.000  
##  Max.   :5.000   Max.   :5.000   Max.   :5.000   Max.   :5.000   Max.   :5.000   Max.   :5.000   Max.   :5.000   Max.   :5.000   Max.   :5.000   Max.   :5.000   Max.   :5.000   Max.   :5.000  
##                                                                                                                                                                                                 
##       i49             i50            i51             i52             i53             i54             i55            i56             i57             i58             i59             i60       
##  Min.   :1.000   Min.   :1.00   Min.   :1.000   Min.   :1.000   Min.   :1.000   Min.   :1.000   Min.   :1.00   Min.   :1.000   Min.   :1.000   Min.   :1.000   Min.   :1.000   Min.   :1.000  
##  1st Qu.:2.000   1st Qu.:3.00   1st Qu.:2.000   1st Qu.:4.000   1st Qu.:3.000   1st Qu.:2.000   1st Qu.:3.00   1st Qu.:3.000   1st Qu.:2.000   1st Qu.:2.000   1st Qu.:2.000   1st Qu.:3.000  
##  Median :3.000   Median :4.00   Median :3.000   Median :4.000   Median :4.000   Median :3.000   Median :4.00   Median :4.000   Median :3.000   Median :3.000   Median :3.000   Median :4.000  
##  Mean   :3.293   Mean   :3.65   Mean   :2.971   Mean   :4.199   Mean   :3.525   Mean   :2.746   Mean   :3.52   Mean   :3.573   Mean   :2.926   Mean   :2.943   Mean   :2.876   Mean   :3.452  
##  3rd Qu.:4.000   3rd Qu.:5.00   3rd Qu.:4.000   3rd Qu.:5.000   3rd Qu.:4.000   3rd Qu.:4.000   3rd Qu.:4.00   3rd Qu.:4.000   3rd Qu.:4.000   3rd Qu.:4.000   3rd Qu.:4.000   3rd Qu.:4.000  
##  Max.   :5.000   Max.   :5.00   Max.   :5.000   Max.   :5.000   Max.   :5.000   Max.   :5.000   Max.   :5.00   Max.   :5.000   Max.   :5.000   Max.   :5.000   Max.   :5.000   Max.   :5.000  
##                                                                                                                                                                                               
##      Gender            Age             Educ      
##  Min.   :0.0000   Min.   :15.00   Min.   :2.000  
##  1st Qu.:0.0000   1st Qu.:18.00   1st Qu.:2.000  
##  Median :0.0000   Median :20.00   Median :3.000  
##  Mean   :0.4212   Mean   :20.06   Mean   :3.701  
##  3rd Qu.:1.0000   3rd Qu.:22.00   3rd Qu.:5.000  
##  Max.   :1.0000   Max.   :26.00   Max.   :8.000  
##                                   NA&#39;s   :1010</code></pre>
</details>
<details>
<summary>
<code>str()</code>
</summary>
<pre class="r"><code>str(BFI2)</code></pre>
<pre><code>## &#39;data.frame&#39;:    1733 obs. of  63 variables:
##  $ i1    : num  5 4 1 4 5 3 3 4 4 4 ...
##  $ i2    : num  5 5 4 5 5 5 4 4 5 5 ...
##  $ i3    : num  2 4 3 1 2 2 2 3 5 1 ...
##  $ i4    : num  3 3 5 4 2 3 4 3 3 2 ...
##  $ i5    : num  5 3 2 5 4 4 5 4 5 3 ...
##  $ i6    : num  4 3 1 3 5 3 3 2 3 4 ...
##  $ i7    : num  4 5 3 5 5 4 4 4 5 4 ...
##  $ i8    : num  3 3 1 2 3 1 3 4 2 1 ...
##  $ i9    : num  4 2 5 4 3 3 4 3 2 3 ...
##  $ i10   : num  5 4 4 3 4 5 4 4 2 4 ...
##  $ i11   : num  5 4 4 3 4 4 4 5 4 3 ...
##  $ i12   : num  4 2 1 5 3 4 2 3 2 4 ...
##  $ i13   : num  3 4 5 4 4 3 4 4 2 2 ...
##  $ i14   : num  4 2 5 2 5 5 4 1 4 4 ...
##  $ i15   : num  2 3 2 2 5 2 4 5 4 4 ...
##  $ i16   : num  3 4 1 3 5 1 2 3 2 2 ...
##  $ i17   : num  5 5 5 5 5 5 4 5 5 4 ...
##  $ i18   : num  3 4 5 2 3 1 4 1 3 2 ...
##  $ i19   : num  2 3 5 2 4 3 4 2 2 4 ...
##  $ i20   : num  5 4 5 5 4 2 3 4 5 5 ...
##  $ i21   : num  4 4 1 2 5 1 3 1 2 3 ...
##  $ i22   : num  4 4 2 5 3 5 5 5 5 4 ...
##  $ i23   : num  4 4 1 2 4 4 3 4 2 1 ...
##  $ i24   : num  3 2 5 3 2 2 2 4 2 2 ...
##  $ i25   : num  5 2 3 4 4 1 2 3 4 5 ...
##  $ i26   : num  4 4 1 3 4 3 4 5 2 4 ...
##  $ i27   : num  4 2 1 5 4 4 3 4 4 5 ...
##  $ i28   : num  5 4 4 4 4 3 4 4 2 2 ...
##  $ i29   : num  5 3 5 2 4 4 5 2 2 2 ...
##  $ i30   : num  5 4 2 3 4 2 5 5 5 4 ...
##  $ i31   : num  3 5 1 2 4 1 2 2 2 2 ...
##  $ i32   : num  5 5 3 5 5 4 4 4 3 4 ...
##  $ i33   : num  4 5 5 2 3 2 4 1 2 1 ...
##  $ i34   : num  4 4 5 5 5 2 5 3 2 4 ...
##  $ i35   : num  5 5 5 5 5 3 5 3 5 5 ...
##  $ i36   : num  4 3 5 3 4 3 3 1 4 3 ...
##  $ i37   : num  3 4 2 5 2 2 4 5 5 4 ...
##  $ i38   : num  4 4 1 2 5 4 4 3 4 4 ...
##  $ i39   : num  2 1 5 3 4 5 4 3 1 3 ...
##  $ i40   : num  4 4 5 4 4 3 4 4 4 4 ...
##  $ i41   : num  4 4 3 2 3 4 3 5 3 3 ...
##  $ i42   : num  5 3 2 5 3 2 4 4 4 4 ...
##  $ i43   : num  5 4 5 5 4 4 4 4 4 4 ...
##  $ i44   : num  4 2 1 2 2 5 4 2 3 2 ...
##  $ i45   : num  5 4 1 2 4 3 4 5 5 5 ...
##  $ i46   : num  4 4 1 2 5 4 4 4 2 4 ...
##  $ i47   : num  2 4 1 5 3 3 2 4 5 4 ...
##  $ i48   : num  2 5 5 4 4 2 4 3 4 1 ...
##  $ i49   : num  2 2 5 4 4 5 4 5 3 4 ...
##  $ i50   : num  5 4 4 5 5 4 3 4 5 4 ...
##  $ i51   : num  4 4 1 1 4 1 2 1 2 2 ...
##  $ i52   : num  5 5 5 5 5 4 4 5 5 4 ...
##  $ i53   : num  5 4 1 4 5 3 4 2 3 4 ...
##  $ i54   : num  2 1 5 4 4 4 5 4 1 3 ...
##  $ i55   : num  5 4 2 4 4 1 3 1 5 5 ...
##  $ i56   : num  5 4 4 4 4 4 4 5 2 4 ...
##  $ i57   : num  5 3 1 5 3 3 2 2 4 3 ...
##  $ i58   : num  1 3 4 2 4 2 3 2 2 2 ...
##  $ i59   : num  4 2 5 2 3 4 4 2 2 2 ...
##  $ i60   : num  2 3 2 2 4 2 4 5 5 4 ...
##  $ Gender: num  0 0 0 0 0 0 0 0 0 1 ...
##  $ Age   : num  21 25 22 21 21 19 21 22 20 21 ...
##  $ Educ  : num  NA NA NA NA NA NA NA NA NA NA ...</code></pre>
</details>
<pre class="r"><code>head(BFI2)</code></pre>
<div data-pagedtable="false">
<script data-pagedtable-source type="application/json">
{"columns":[{"label":[""],"name":["_rn_"],"type":[""],"align":["left"]},{"label":["i1"],"name":[1],"type":["dbl"],"align":["right"]},{"label":["i2"],"name":[2],"type":["dbl"],"align":["right"]},{"label":["i3"],"name":[3],"type":["dbl"],"align":["right"]},{"label":["i4"],"name":[4],"type":["dbl"],"align":["right"]},{"label":["i5"],"name":[5],"type":["dbl"],"align":["right"]},{"label":["i6"],"name":[6],"type":["dbl"],"align":["right"]},{"label":["i7"],"name":[7],"type":["dbl"],"align":["right"]},{"label":["i8"],"name":[8],"type":["dbl"],"align":["right"]},{"label":["i9"],"name":[9],"type":["dbl"],"align":["right"]},{"label":["i10"],"name":[10],"type":["dbl"],"align":["right"]},{"label":["i11"],"name":[11],"type":["dbl"],"align":["right"]},{"label":["i12"],"name":[12],"type":["dbl"],"align":["right"]},{"label":["i13"],"name":[13],"type":["dbl"],"align":["right"]},{"label":["i14"],"name":[14],"type":["dbl"],"align":["right"]},{"label":["i15"],"name":[15],"type":["dbl"],"align":["right"]},{"label":["i16"],"name":[16],"type":["dbl"],"align":["right"]},{"label":["i17"],"name":[17],"type":["dbl"],"align":["right"]},{"label":["i18"],"name":[18],"type":["dbl"],"align":["right"]},{"label":["i19"],"name":[19],"type":["dbl"],"align":["right"]},{"label":["i20"],"name":[20],"type":["dbl"],"align":["right"]},{"label":["i21"],"name":[21],"type":["dbl"],"align":["right"]},{"label":["i22"],"name":[22],"type":["dbl"],"align":["right"]},{"label":["i23"],"name":[23],"type":["dbl"],"align":["right"]},{"label":["i24"],"name":[24],"type":["dbl"],"align":["right"]},{"label":["i25"],"name":[25],"type":["dbl"],"align":["right"]},{"label":["i26"],"name":[26],"type":["dbl"],"align":["right"]},{"label":["i27"],"name":[27],"type":["dbl"],"align":["right"]},{"label":["i28"],"name":[28],"type":["dbl"],"align":["right"]},{"label":["i29"],"name":[29],"type":["dbl"],"align":["right"]},{"label":["i30"],"name":[30],"type":["dbl"],"align":["right"]},{"label":["i31"],"name":[31],"type":["dbl"],"align":["right"]},{"label":["i32"],"name":[32],"type":["dbl"],"align":["right"]},{"label":["i33"],"name":[33],"type":["dbl"],"align":["right"]},{"label":["i34"],"name":[34],"type":["dbl"],"align":["right"]},{"label":["i35"],"name":[35],"type":["dbl"],"align":["right"]},{"label":["i36"],"name":[36],"type":["dbl"],"align":["right"]},{"label":["i37"],"name":[37],"type":["dbl"],"align":["right"]},{"label":["i38"],"name":[38],"type":["dbl"],"align":["right"]},{"label":["i39"],"name":[39],"type":["dbl"],"align":["right"]},{"label":["i40"],"name":[40],"type":["dbl"],"align":["right"]},{"label":["i41"],"name":[41],"type":["dbl"],"align":["right"]},{"label":["i42"],"name":[42],"type":["dbl"],"align":["right"]},{"label":["i43"],"name":[43],"type":["dbl"],"align":["right"]},{"label":["i44"],"name":[44],"type":["dbl"],"align":["right"]},{"label":["i45"],"name":[45],"type":["dbl"],"align":["right"]},{"label":["i46"],"name":[46],"type":["dbl"],"align":["right"]},{"label":["i47"],"name":[47],"type":["dbl"],"align":["right"]},{"label":["i48"],"name":[48],"type":["dbl"],"align":["right"]},{"label":["i49"],"name":[49],"type":["dbl"],"align":["right"]},{"label":["i50"],"name":[50],"type":["dbl"],"align":["right"]},{"label":["i51"],"name":[51],"type":["dbl"],"align":["right"]},{"label":["i52"],"name":[52],"type":["dbl"],"align":["right"]},{"label":["i53"],"name":[53],"type":["dbl"],"align":["right"]},{"label":["i54"],"name":[54],"type":["dbl"],"align":["right"]},{"label":["i55"],"name":[55],"type":["dbl"],"align":["right"]},{"label":["i56"],"name":[56],"type":["dbl"],"align":["right"]},{"label":["i57"],"name":[57],"type":["dbl"],"align":["right"]},{"label":["i58"],"name":[58],"type":["dbl"],"align":["right"]},{"label":["i59"],"name":[59],"type":["dbl"],"align":["right"]},{"label":["i60"],"name":[60],"type":["dbl"],"align":["right"]},{"label":["Gender"],"name":[61],"type":["dbl"],"align":["right"]},{"label":["Age"],"name":[62],"type":["dbl"],"align":["right"]},{"label":["Educ"],"name":[63],"type":["dbl"],"align":["right"]}],"data":[{"1":"5","2":"5","3":"2","4":"3","5":"5","6":"4","7":"4","8":"3","9":"4","10":"5","11":"5","12":"4","13":"3","14":"4","15":"2","16":"3","17":"5","18":"3","19":"2","20":"5","21":"4","22":"4","23":"4","24":"3","25":"5","26":"4","27":"4","28":"5","29":"5","30":"5","31":"3","32":"5","33":"4","34":"4","35":"5","36":"4","37":"3","38":"4","39":"2","40":"4","41":"4","42":"5","43":"5","44":"4","45":"5","46":"4","47":"2","48":"2","49":"2","50":"5","51":"4","52":"5","53":"5","54":"2","55":"5","56":"5","57":"5","58":"1","59":"4","60":"2","61":"0","62":"21","63":"NA","_rn_":"1"},{"1":"4","2":"5","3":"4","4":"3","5":"3","6":"3","7":"5","8":"3","9":"2","10":"4","11":"4","12":"2","13":"4","14":"2","15":"3","16":"4","17":"5","18":"4","19":"3","20":"4","21":"4","22":"4","23":"4","24":"2","25":"2","26":"4","27":"2","28":"4","29":"3","30":"4","31":"5","32":"5","33":"5","34":"4","35":"5","36":"3","37":"4","38":"4","39":"1","40":"4","41":"4","42":"3","43":"4","44":"2","45":"4","46":"4","47":"4","48":"5","49":"2","50":"4","51":"4","52":"5","53":"4","54":"1","55":"4","56":"4","57":"3","58":"3","59":"2","60":"3","61":"0","62":"25","63":"NA","_rn_":"2"},{"1":"1","2":"4","3":"3","4":"5","5":"2","6":"1","7":"3","8":"1","9":"5","10":"4","11":"4","12":"1","13":"5","14":"5","15":"2","16":"1","17":"5","18":"5","19":"5","20":"5","21":"1","22":"2","23":"1","24":"5","25":"3","26":"1","27":"1","28":"4","29":"5","30":"2","31":"1","32":"3","33":"5","34":"5","35":"5","36":"5","37":"2","38":"1","39":"5","40":"5","41":"3","42":"2","43":"5","44":"1","45":"1","46":"1","47":"1","48":"5","49":"5","50":"4","51":"1","52":"5","53":"1","54":"5","55":"2","56":"4","57":"1","58":"4","59":"5","60":"2","61":"0","62":"22","63":"NA","_rn_":"3"},{"1":"4","2":"5","3":"1","4":"4","5":"5","6":"3","7":"5","8":"2","9":"4","10":"3","11":"3","12":"5","13":"4","14":"2","15":"2","16":"3","17":"5","18":"2","19":"2","20":"5","21":"2","22":"5","23":"2","24":"3","25":"4","26":"3","27":"5","28":"4","29":"2","30":"3","31":"2","32":"5","33":"2","34":"5","35":"5","36":"3","37":"5","38":"2","39":"3","40":"4","41":"2","42":"5","43":"5","44":"2","45":"2","46":"2","47":"5","48":"4","49":"4","50":"5","51":"1","52":"5","53":"4","54":"4","55":"4","56":"4","57":"5","58":"2","59":"2","60":"2","61":"0","62":"21","63":"NA","_rn_":"4"},{"1":"5","2":"5","3":"2","4":"2","5":"4","6":"5","7":"5","8":"3","9":"3","10":"4","11":"4","12":"3","13":"4","14":"5","15":"5","16":"5","17":"5","18":"3","19":"4","20":"4","21":"5","22":"3","23":"4","24":"2","25":"4","26":"4","27":"4","28":"4","29":"4","30":"4","31":"4","32":"5","33":"3","34":"5","35":"5","36":"4","37":"2","38":"5","39":"4","40":"4","41":"3","42":"3","43":"4","44":"2","45":"4","46":"5","47":"3","48":"4","49":"4","50":"5","51":"4","52":"5","53":"5","54":"4","55":"4","56":"4","57":"3","58":"4","59":"3","60":"4","61":"0","62":"21","63":"NA","_rn_":"5"},{"1":"3","2":"5","3":"2","4":"3","5":"4","6":"3","7":"4","8":"1","9":"3","10":"5","11":"4","12":"4","13":"3","14":"5","15":"2","16":"1","17":"5","18":"1","19":"3","20":"2","21":"1","22":"5","23":"4","24":"2","25":"1","26":"3","27":"4","28":"3","29":"4","30":"2","31":"1","32":"4","33":"2","34":"2","35":"3","36":"3","37":"2","38":"4","39":"5","40":"3","41":"4","42":"2","43":"4","44":"5","45":"3","46":"4","47":"3","48":"2","49":"5","50":"4","51":"1","52":"4","53":"3","54":"4","55":"1","56":"4","57":"3","58":"2","59":"4","60":"2","61":"0","62":"19","63":"NA","_rn_":"6"}],"options":{"columns":{"min":{},"max":[10]},"rows":{"min":[10],"max":[10]},"pages":{}}}
  </script>
</div>
<pre class="r"><code># data names
names(BFI2)</code></pre>
<pre><code>##  [1] &quot;i1&quot;     &quot;i2&quot;     &quot;i3&quot;     &quot;i4&quot;     &quot;i5&quot;     &quot;i6&quot;     &quot;i7&quot;     &quot;i8&quot;     &quot;i9&quot;     &quot;i10&quot;    &quot;i11&quot;    &quot;i12&quot;    &quot;i13&quot;    &quot;i14&quot;    &quot;i15&quot;    &quot;i16&quot;    &quot;i17&quot;    &quot;i18&quot;    &quot;i19&quot;    &quot;i20&quot;    &quot;i21&quot;   
## [22] &quot;i22&quot;    &quot;i23&quot;    &quot;i24&quot;    &quot;i25&quot;    &quot;i26&quot;    &quot;i27&quot;    &quot;i28&quot;    &quot;i29&quot;    &quot;i30&quot;    &quot;i31&quot;    &quot;i32&quot;    &quot;i33&quot;    &quot;i34&quot;    &quot;i35&quot;    &quot;i36&quot;    &quot;i37&quot;    &quot;i38&quot;    &quot;i39&quot;    &quot;i40&quot;    &quot;i41&quot;    &quot;i42&quot;   
## [43] &quot;i43&quot;    &quot;i44&quot;    &quot;i45&quot;    &quot;i46&quot;    &quot;i47&quot;    &quot;i48&quot;    &quot;i49&quot;    &quot;i50&quot;    &quot;i51&quot;    &quot;i52&quot;    &quot;i53&quot;    &quot;i54&quot;    &quot;i55&quot;    &quot;i56&quot;    &quot;i57&quot;    &quot;i58&quot;    &quot;i59&quot;    &quot;i60&quot;    &quot;Gender&quot; &quot;Age&quot;    &quot;Educ&quot;</code></pre>
<pre class="r"><code>colnames(BFI2)[1:60] &lt;- c(&quot;iEscb01&quot;, &quot;iAcmp02&quot;, &quot;iCorg03r&quot;, &quot;iNanx04r&quot;, &quot;iOaes05r&quot;, &quot;iEasr06&quot;,
&quot;iArsp07&quot;, &quot;iCprd08r&quot;, &quot;iNdep09r&quot;, &quot;iOint10&quot;, &quot;iEenl11r&quot;, &quot;iAtrs12r&quot;, &quot;iCrsp13&quot;, &quot;iNemt14&quot;,
&quot;iOcrt15&quot;, &quot;iEscb16r&quot;, &quot;iAcmp17r&quot;, &quot;iCorg18&quot;, &quot;iNanx19&quot;, &quot;iOaes20&quot;, &quot;iEasr21&quot;, &quot;iArsp22r&quot;,
&quot;iCprd23r&quot;, &quot;iNdep24r&quot;, &quot;iOint25r&quot;, &quot;iEenl26r&quot;, &quot;iAtrs27&quot;, &quot;iCrsp28r&quot;, &quot;iNemt29r&quot;,
&quot;iOcrt30r&quot;, &quot;iEscb31r&quot;, &quot;iAcmp32&quot;, &quot;iCorg33&quot;, &quot;iNanx34&quot;, &quot;iOaes35&quot;, &quot;iEasr36r&quot;, &quot;iArsp37r&quot;,
&quot;iCprd38&quot;, &quot;iNdep39&quot;, &quot;iOint40&quot;, &quot;iEenl41&quot;, &quot;iAtrs42r&quot;, &quot;iCrsp43&quot;, &quot;iNemt44r&quot;, &quot;iOcrt45r&quot;,
&quot;iEscb46&quot;, &quot;iAcmp47r&quot;, &quot;iCorg48r&quot;, &quot;iNanx49r&quot;, &quot;iOaes50r&quot;, &quot;iEasr51r&quot;, &quot;iArsp52&quot;, &quot;iCprd53&quot;,
&quot;iNdep54&quot;, &quot;iOint55r&quot;, &quot;iEenl56&quot;, &quot;iAtrs57&quot;, &quot;iCrsp58r&quot;, &quot;iNemt59&quot;, &quot;iOcrt60&quot;)

# Data frames for domains
BFI2_e &lt;- BFI2[, seq(1, 56, 5)]
BFI2_a &lt;- BFI2[, seq(2, 57, 5)]
BFI2_c &lt;- BFI2[, seq(3, 58, 5)]
BFI2_n &lt;- BFI2[, seq(4, 59, 5)]
BFI2_o &lt;- BFI2[, seq(5, 60, 5)]</code></pre>
<pre class="r"><code># data format
BFI2$Gender &lt;- factor(BFI2$Gender, 
                      levels=c(&#39;0&#39;, &#39;1&#39;), 
                      labels=c(&#39;Female&#39;, &#39;Male&#39;))

BFI2$Educ &lt;- factor(BFI2$Educ,
                    levels = c(2:8),
                    labels=c(&quot;Secondary technical school&quot;, &quot;Secondary general school&quot;, &quot;Other secondary school&quot;,
                             &quot;Tertiary professional school&quot;, &quot;Bachelor degree&quot;, 
                             &quot;Masters degree&quot;, &quot;PhD&quot;))</code></pre>
<pre class="r"><code># descriptive statistics for Gender, Age and Educ
round(prop.table(table(BFI2$Gender)), 3)</code></pre>
<pre><code>## 
## Female   Male 
##  0.579  0.421</code></pre>
<pre class="r"><code>summary(BFI2$Age)</code></pre>
<pre><code>##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
##   15.00   18.00   20.00   20.06   22.00   26.00</code></pre>
<pre class="r"><code>summary(BFI2$Educ)</code></pre>
<pre><code>##   Secondary technical school     Secondary general school       Other secondary school Tertiary professional school              Bachelor degree               Masters degree 
##                          232                          202                           97                           29                           75                           81 
##                          PhD                         NA&#39;s 
##                            7                         1010</code></pre>
<pre class="r"><code>round(prop.table(table(BFI2$Educ)), 3)</code></pre>
<pre><code>## 
##   Secondary technical school     Secondary general school       Other secondary school Tertiary professional school              Bachelor degree               Masters degree 
##                        0.321                        0.279                        0.134                        0.040                        0.104                        0.112 
##                          PhD 
##                        0.010</code></pre>
<pre class="r"><code>educ &lt;- as.data.frame(table(BFI2$Educ, dnn = list(&quot;Education&quot;)), responseName = &quot;Count&quot;)</code></pre>
<pre class="r"><code># gender
ggplot(BFI2, aes(Gender, fill = Gender)) +
  geom_bar() +
  theme_bw() +
  ggtitle(&quot;Gender&quot;) +
  theme(plot.title = element_text(hjust=0.5),
        axis.title.x = element_blank())</code></pre>
<p><img src="HW2_files/figure-html/plots-1.png" width="672" /></p>
<pre class="r"><code># age
ggplot(BFI2, 
       aes(Age)) +
  geom_histogram(bins = 12, fill = &#39;coral1&#39;, col=&#39;white&#39;) +
  theme_bw() +
  ggtitle(&quot;Age&quot;) +
  theme(plot.title = element_text(hjust=0.5),
        axis.title.x = element_blank())</code></pre>
<p><img src="HW2_files/figure-html/plots-2.png" width="672" /></p>
<pre class="r"><code># educ
ggplot(educ, aes(x=reorder(Education, +Count), y=Count, fill = Education)) +
  geom_bar(stat = &quot;identity&quot;) +
  labs(title = &quot;Education&quot;) +
  theme_bw() +
    theme(legend.position=&quot;none&quot;,
        plot.title = element_text(hjust=0.5),
        axis.title.y = element_blank()) + 
  coord_flip()</code></pre>
<p><img src="HW2_files/figure-html/plots-3.png" width="672" /></p>
<pre class="r"><code># facet scores
facets &lt;- unique(substr(names(BFI2[1:60]), 2,5))
BFI2_facets &lt;- as.data.frame(sapply(facets, function(xx) rowSums(BFI2[,grep(xx, names(BFI2)), drop=FALSE])))

# domain scores
domains &lt;- unique(substr(names(BFI2[1:60]), 2, 2))
BFI2_domains &lt;- as.data.frame(sapply(domains, function(xx) rowSums(BFI2_facets[,grep(xx, names(BFI2_facets)), drop=FALSE])))
BFI2_domains &lt;- cbind(BFI2_domains, BFI2$Gender, BFI2$Educ)
colnames(BFI2_domains)[6:7] &lt;- c(&quot;Gender&quot;, &quot;Education&quot;)</code></pre>
<pre class="r"><code># item scores to long format
BFI2_long &lt;- BFI2 %&gt;% 
  mutate(pid = row_number()) %&gt;% 
  pivot_longer(starts_with(&quot;i&quot;), names_to =&quot;Item&quot;, values_to = &quot;Score&quot;) %&gt;% 
  mutate(Domain = substr(Item, 2, 2),
         Facet = substr(Item, 2, 5))</code></pre>
<pre class="r"><code># domain scores to long format
BFI2_domains_long &lt;- BFI2_domains %&gt;% 
  mutate(pid = row_number()) %&gt;% 
  pivot_longer(cols = 1:5, names_to = &quot;Domain&quot;, values_to = &quot;Score&quot;) %&gt;% 
  mutate(Domain = as.factor(Domain))

# descriptive stats for domains
describeBy(BFI2_long$Score, group=BFI2_long$Domain)</code></pre>
<pre><code>## 
##  Descriptive statistics by group 
## group: A
##    vars     n mean   sd median trimmed  mad min max range  skew kurtosis   se
## X1    1 20796 3.61 1.12      4    3.69 1.48   1   5     4 -0.58    -0.51 0.01
## -------------------------------------------------------------------------------------------------------------------------------------------------- 
## group: C
##    vars     n mean   sd median trimmed  mad min max range  skew kurtosis   se
## X1    1 20796 3.23 1.15      3    3.25 1.48   1   5     4 -0.23    -0.88 0.01
## -------------------------------------------------------------------------------------------------------------------------------------------------- 
## group: E
##    vars     n mean   sd median trimmed  mad min max range  skew kurtosis   se
## X1    1 20796  3.3 1.15      3    3.33 1.48   1   5     4 -0.29    -0.82 0.01
## -------------------------------------------------------------------------------------------------------------------------------------------------- 
## group: N
##    vars     n mean   sd median trimmed  mad min max range skew kurtosis   se
## X1    1 20796 2.97 1.18      3    2.96 1.48   1   5     4 0.03       -1 0.01
## -------------------------------------------------------------------------------------------------------------------------------------------------- 
## group: O
##    vars     n mean   sd median trimmed  mad min max range  skew kurtosis   se
## X1    1 20796 3.62 1.12      4    3.71 1.48   1   5     4 -0.56     -0.5 0.01</code></pre>
<pre class="r"><code># descriptive stats grouped by domain &amp; gender
describeBy(BFI2_domains_long$Score, group = list(BFI2_domains_long$Domain, BFI2_domains_long$Gender))</code></pre>
<pre><code>## 
##  Descriptive statistics by group 
## : A
## : Female
##    vars    n mean   sd median trimmed  mad min max range  skew kurtosis  se
## X1    1 1003 44.3 6.37     45   44.54 5.93  20  60    40 -0.42     0.22 0.2
## -------------------------------------------------------------------------------------------------------------------------------------------------- 
## : C
## : Female
##    vars    n  mean   sd median trimmed mad min max range  skew kurtosis   se
## X1    1 1003 39.23 8.48     40   39.38 8.9  12  60    48 -0.17    -0.45 0.27
## -------------------------------------------------------------------------------------------------------------------------------------------------- 
## : E
## : Female
##    vars    n  mean   sd median trimmed mad min max range  skew kurtosis   se
## X1    1 1003 39.51 8.18     40   39.53 8.9  18  59    41 -0.03    -0.55 0.26
## -------------------------------------------------------------------------------------------------------------------------------------------------- 
## : N
## : Female
##    vars    n  mean   sd median trimmed   mad min max range skew kurtosis   se
## X1    1 1003 37.61 8.76     37   37.56 10.38  13  59    46 0.03    -0.54 0.28
## -------------------------------------------------------------------------------------------------------------------------------------------------- 
## : O
## : Female
##    vars    n  mean   sd median trimmed  mad min max range  skew kurtosis   se
## X1    1 1003 43.81 7.59     44   43.95 7.41  22  60    38 -0.18    -0.36 0.24
## -------------------------------------------------------------------------------------------------------------------------------------------------- 
## : A
## : Male
##    vars   n  mean   sd median trimmed  mad min max range  skew kurtosis   se
## X1    1 730 41.95 7.11     42    42.1 7.41  19  60    41 -0.23    -0.08 0.26
## -------------------------------------------------------------------------------------------------------------------------------------------------- 
## : C
## : Male
##    vars   n  mean   sd median trimmed  mad min max range  skew kurtosis  se
## X1    1 730 38.09 8.11     38   38.12 7.41  12  60    48 -0.02     -0.2 0.3
## -------------------------------------------------------------------------------------------------------------------------------------------------- 
## : E
## : Male
##    vars   n  mean   sd median trimmed mad min max range  skew kurtosis   se
## X1    1 730 39.71 8.47     40   39.83 8.9  17  59    42 -0.13    -0.54 0.31
## -------------------------------------------------------------------------------------------------------------------------------------------------- 
## : N
## : Male
##    vars   n  mean   sd median trimmed mad min max range skew kurtosis   se
## X1    1 730 32.92 9.24     32   32.74 8.9  12  60    48 0.24    -0.16 0.34
## -------------------------------------------------------------------------------------------------------------------------------------------------- 
## : O
## : Male
##    vars   n  mean  sd median trimmed mad min max range  skew kurtosis   se
## X1    1 730 43.04 7.9     43   43.08 8.9  19  60    41 -0.07    -0.46 0.29</code></pre>
<pre class="r"><code># plot of domain distributions &amp; gender
ggplot(BFI2_domains_long, aes(x=Score, y=Domain)) + 
  geom_density_ridges(aes(group = interaction(Domain, Gender), fill = Gender, linetype=Gender),
               position = &quot;identity&quot;,
               alpha = 0.7,
               size = 1) +
  labs(title = &quot;Distribution of Big5 domains&quot;, x = &quot;Score&quot;) +
  scale_y_discrete(labels=c(&quot;Open-Mindedness&quot;, &quot;Negative Emotionality&quot;, 
                            &quot;Extraversion&quot;, &quot;Conscientiousness&quot;, &quot;Agreeability&quot;)) +
  theme_bw() +
  theme(axis.title.y = element_blank(),
        plot.title = element_text(hjust=0.5))</code></pre>
<p><img src="HW2_files/figure-html/unnamed-chunk-9-1.png" width="672" /></p>
<p>We decided to work with the <code>BFI2</code>dataset from the <code>ShinyItemAnalysis</code> package. The <code>BFI2</code>dataset contains responses of <span class="math inline">\(1733\)</span> Czech respondents to the Big Five Inventory 2, as well as information about their age, education, and gender. The BFI2 items are scored using a 5-point Likert scale. I used alternative item names provided in the dataset documentation and I set both the <code>Gender</code> and <code>Educ</code> variables to factors with appropriate labels. Circa <span class="math inline">\(57.9 \%\)</span> of the respondents are female, <span class="math inline">\(42.1 \%\)</span> are male. Notably, the dataset only covers an age group of people between <span class="math inline">\(15\)</span> and <span class="math inline">\(26\)</span> with a mean of <span class="math inline">\(20.06\)</span> years. Out of the <span class="math inline">\(723\)</span> respondents who specified their highest level of attained education – <span class="math inline">\(32.1 \%\)</span> finished a secondary technical school, <span class="math inline">\(27.9 \%\)</span> finished a secondary general school, <span class="math inline">\(13.4 \%\)</span> finished another secondary school, <span class="math inline">\(11.2 \%\)</span> obtained a Masters degree, <span class="math inline">\(10.4 \%\)</span> obtained a Bachelor degree, <span class="math inline">\(4 \%\)</span> finished a tertiary professional school and finally, <span class="math inline">\(1 \%\)</span> obtained a PhD.</p>
<p>When observing the distribution of scores grouped by the Big5 domains it can be stated that they do not follow a normal distribution – they are multimodal. <em>Open-Mindedness</em> has the highest mean in this sample (<span class="math inline">\(43.48\)</span>) followed by <em>Agreeability</em> (<span class="math inline">\(43.31\)</span>), <em>Extraversion</em> (<span class="math inline">\(39.59\)</span>), <em>Conscientiousness</em> (<span class="math inline">\(38.75\)</span>) and <em>Negative Emotionality</em> (35.63). <em>Negative Emotionality</em> exhibits the highest standard deviation, which points to relatively spread out responses on the corresponding items. It could be hypothesized, that these results are, to a certain extent, typical of the given age group (e.g. high <em>Open-Mindedness</em>). On average, female respondents in this sample scored higher than males in all dimensions except <em>Extraversion</em>. The most distinct gender differences in this sample seem to emerge along the dimensions of <em>Negative Emotionaliy</em> (<span class="math inline">\(\mu_{(F)} = 37.61\)</span>, <span class="math inline">\(\mu_{(M)} = 32.92\)</span>) and <em>Agreeability</em> (<span class="math inline">\(\mu_{(F)} = 44.3\)</span>, <span class="math inline">\(\mu_{(M)} = 41.95\)</span>).</p>
<p></br></p>
</div>
<div id="b.-what-construct-is-your-test-measuring-what-is-intended-use-of-test-scores-is-there-other-use-you-can-think-of" class="section level5">
<h5>4b. What construct is your test measuring? What is intended use of test scores? Is there other use you can think of?</h5>
<p>The Big Five is a 5-factor model of personality – therefore, inventories based on this model measure 5 personality traits. The test scores are primarily intended to capture and summarize important personality differences, which is especially useful in psychological research. The <em>Neuroticism</em>/<em>Negative Emotionality</em> scale is particularly beneficial in clinical psychology. Big Five inventories can also be utilized in career counseling (identifying personal strengths) or in candidate assessment (comparing candidate’s profile to an ideal one). Apart from the broad 5 personality dimensions, Big Five inventories generally also contain more specific subscales (e.g. <em>Sociability</em>) which allow for more precise predictions of behavior.</p>
<p></br></p>
</div>
<div id="c-how-would-you-obtain-evidence-of-validity-of-test-scores-based-on-test-content-how-would-you-obtain-evidence-of-criterion-validity-what-data-would-you-need-use-terms-concurrent-predictive-incremental-convergent-discriminant.-provide-proofs-of-criterion-validity-if-criterion-is-available." class="section level5">
<h5>4c How would you obtain evidence of validity of test scores based on test content? How would you obtain evidence of criterion validity, what data would you need? Use terms concurrent, predictive, incremental, convergent, discriminant. Provide proofs of criterion validity if criterion is available.</h5>
<p>Since the BFI2 is a self-report inventory, evidence of construct validity could be obtained by examining rater-concordance between the respondents and their friends, or between respondents and experts (psychiatrists, clinical psychologists). Test content validity could be determined by experts’ ratings of the importance/suitability of the individual items.</p>
<p>Evidence for the <strong>convergent validity</strong> of the Big Five could be obtained by correlating the domain scores with other psychological tests aiming to measure the same or at least similar constructs. One could for example compare the BFI2 results to reults of the NEO PI-R. Furthermore, one could for example expect the subscale of <em>Negative Emotionality</em> to correlate with measures of anxiety (e.g. Generalized Anxiety Disorder Assessment) and depression (Beck’s Depression Inventory). <em>Open-Mindedness</em> should presumably correlate with measures of creativity etc.</p>
<p><strong>Discriminant validity</strong> of the BFI2 could be explored by comparing the results of its subscales to constructs, that should not be highly correlated to said subscales. Going back to the previously mentioned GAD and BDI as correlates of the <em>Negative Emotionality</em> subscale, one should make sure that the correlations aren’t extremely high, and that the tests aren’t measuring identical constructs.</p>
<p><strong>Concurrent validity</strong> could be assessed by comparing the BFI2 results with another personality test based on the Big Five model administrated at the same time.</p>
<p>We could obtain evidence for the BIF2’s <strong>predictive validity</strong> for example by correlating <em>Conscientiousness</em> scores of students with their future GPAs, or scores of employees with their future job performance. <em>Negative Emotionality</em> could serve as a predictor of certain clinical diagnoses (anxiety, personality disorders, mood disorders).</p>
<p>An example of evidence for <strong>incremental validity</strong> of the BFI2 could be the comparison of the predictive value of <em>Conscientiousness</em> scores (in terms of future job performance) to other measures of candidate assessment, such as an assessment centre.</p>
<p></br></p>
</div>
<div id="d-provide-evidence-of-validity-of-test-scores-based-on-internal-structure-include-corrplot-discuss-which-items-correlate-the-most." class="section level5">
<h5>4d Provide evidence of validity of test scores based on internal structure: Include corrplot, discuss which items correlate the most.</h5>
<pre class="r"><code># item correlation matrix
corP &lt;- psych::polychoric(BFI2[1:60])

# item correlation plot
ShinyItemAnalysis::plot_corr(BFI2[1:60], cor = &quot;polychoric&quot;,
                             clust_method = &quot;ward.D2&quot;,
                             n_clust = 5,
                             shape = &#39;square&#39;,
                            line_col = &#39;red&#39;,
                            fill = &#39;red&#39;,
                            fill_alpha = 0.1) +
  theme(axis.text=element_text(size=12))</code></pre>
<p><img src="HW2_files/figure-html/internal_structure-1.png" width="1440" /></p>
<pre class="r"><code># factor correlation matrix
cor(BFI2_domains[1:5], method=&quot;spearman&quot;)</code></pre>
<pre><code>##             E           A           C            N            O
## E  1.00000000  0.05112188  0.16267397 -0.315039775  0.288366364
## A  0.05112188  1.00000000  0.23422490 -0.166753129  0.134280238
## C  0.16267397  0.23422490  1.00000000 -0.178877918  0.042422714
## N -0.31503978 -0.16675313 -0.17887792  1.000000000 -0.006434327
## O  0.28836636  0.13428024  0.04242271 -0.006434327  1.000000000</code></pre>
<pre class="r"><code># factor correlation plot
ShinyItemAnalysis::plot_corr(BFI2_domains[1:5],
                             cor = &quot;spearman&quot;,
                             shape = &#39;square&#39;,
                             labels = TRUE,
                             labels_size = 4)</code></pre>
<p><img src="HW2_files/figure-html/unnamed-chunk-10-1.png" width="672" /></p>
<pre class="r"><code># extraversion subscales correlation matrix
BFI2_e %&gt;% 
  plot_corr(corr = &quot;polychoric&quot;,
          clust_method = &quot;ward.D2&quot;,
          n_clust = 3,
          shape = &#39;square&#39;,
          labels = TRUE,
          labels_size = 4,
          line_col = &#39;red&#39;,
          fill = &#39;red&#39;,
          fill_alpha = 0.1)</code></pre>
<p><img src="HW2_files/figure-html/unnamed-chunk-11-1.png" width="672" /></p>
<pre class="r"><code># agreeability subscales correlation matrix
BFI2_a %&gt;% 
  plot_corr(corr = &quot;polychoric&quot;,
          clust_method = &quot;ward.D2&quot;,
          n_clust = 3,
          shape = &#39;square&#39;,
          labels = TRUE,
          labels_size = 4,
          line_col = &#39;red&#39;,
          fill = &#39;red&#39;,
          fill_alpha = 0.1)</code></pre>
<p><img src="HW2_files/figure-html/unnamed-chunk-12-1.png" width="672" /></p>
<pre class="r"><code># conscientiousness subscales correlation matrix
BFI2_c %&gt;% 
  plot_corr(corr = &quot;polychoric&quot;,
          clust_method = &quot;ward.D2&quot;,
          n_clust = 3,
          shape = &#39;square&#39;,
          labels = TRUE,
          labels_size = 4,
          line_col = &#39;red&#39;,
          fill = &#39;red&#39;,
          fill_alpha = 0.1)</code></pre>
<p><img src="HW2_files/figure-html/unnamed-chunk-13-1.png" width="672" /></p>
<pre class="r"><code># negative emotionality subscales correlation matrix
BFI2_n %&gt;% 
  plot_corr(corr = &quot;polychoric&quot;,
          clust_method = &quot;ward.D2&quot;,
          n_clust = 3,
          shape = &#39;square&#39;,
          labels = TRUE,
          labels_size = 4,
          line_col = &#39;red&#39;,
          fill = &#39;red&#39;,
          fill_alpha = 0.1)</code></pre>
<p><img src="HW2_files/figure-html/unnamed-chunk-14-1.png" width="672" /></p>
<pre class="r"><code># open-mindedness subscales correlation matrix
BFI2_o %&gt;% 
  plot_corr(corr = &quot;polychoric&quot;,
          clust_method = &quot;ward.D2&quot;,
          n_clust = 3,
          shape = &#39;square&#39;,
          labels = TRUE,
          labels_size = 4,
          line_col = &#39;red&#39;,
          fill = &#39;red&#39;,
          fill_alpha = 0.1)</code></pre>
<p><img src="HW2_files/figure-html/unnamed-chunk-15-1.png" width="672" /> </br> Because the BFI2 does not measure a single construct, its items should not all intercorrelate. Items should intercorrelate within the framework of the corresponding domain and facet. Although the item correlation heat-map is a bit cluttered, it shows 5 clusters roughly representing the five BFI2 domains. There is an overlap of <em>Extraversion</em> and <em>Open-Mindedness</em> items. Looking at the domain correlations confirms this, as there is a positive correlation (<span class="math inline">\(\rho=0.29\)</span>) between <em>Extraversion</em> and <em>Open-Mindedness</em>. <em>Extraversion</em> is also negatively correlated to <em>Negative Emotionality</em> (<span class="math inline">\(\rho=-0.32\)</span>). Correlation heatmaps for the respective dimensions show that there are a few ‘unexpected’ high correlations – <em>Respectfulness</em> correlates with <em>Compassion</em> (<em>Agreeability</em>), <em>Responsibility</em> correlates with <em>Organization</em> (<em>Conscientiousness</em>), <em>Depression</em> correlates with <em>Anxiety</em> (<em>Negative Emotionality</em>).</p>
<p></br></p>
</div>
<div id="e-extra-discuss-situations-when-range-restriction-may-occur-in-your-data.-simulate-a-situation-when-range-restriction-occurs-in-your-data-or-provide-a-practical-example.-estimate-corrrelation-and-provide-estimate-corrected-for-range-restriction." class="section level5">
<h5>4e (extra) Discuss situations when range restriction may occur in your data. Simulate a situation when range restriction occurs in your data, or provide a practical example. Estimate corrrelation and provide estimate corrected for range restriction.</h5>
<p></br></p>
</div>
</div>
<div id="use-your-own-data-andor-provide-constructive-feedback-to-the-lecture-exercises-or-any-of-the-material.-bonus-1-pt" class="section level4">
<h4>5. Use your own data and/or provide constructive feedback to the lecture, exercises, or any of the material. [BONUS 1 pt]</h4>
<p></br></p>
</div>



</div>
</div>

</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.odd').parent('tbody').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- tabsets -->

<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});

$(document).ready(function () {
  $('.tabset-dropdown > .nav-tabs > li').click(function () {
    $(this).parent().toggleClass('nav-tabs-open');
  });
});
</script>

<!-- code folding -->
<script>
$(document).ready(function () {
  window.initializeCodeFolding("show" === "show");
});
</script>

<script>
$(document).ready(function ()  {

    // temporarily add toc-ignore selector to headers for the consistency with Pandoc
    $('.unlisted.unnumbered').addClass('toc-ignore')

    // move toc-ignore selectors from section div to header
    $('div.section.toc-ignore')
        .removeClass('toc-ignore')
        .children('h1,h2,h3,h4,h5').addClass('toc-ignore');

    // establish options
    var options = {
      selectors: "h1,h2,h3",
      theme: "bootstrap3",
      context: '.toc-content',
      hashGenerator: function (text) {
        return text.replace(/[.\\/?&!#<>]/g, '').replace(/\s/g, '_');
      },
      ignoreSelector: ".toc-ignore",
      scrollTo: 0
    };
    options.showAndHide = true;
    options.smoothScroll = true;

    // tocify
    var toc = $("#TOC").tocify(options).data("toc-tocify");
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
